.circleci/config.yml
Thanks Greg for getting this repo ready!
epic: https://github.com/astronomer/issues/issues/465
A push to any branch will publish:
astronomerinc/ap-airflow:1.10.5-alpine-onbuild
astronomerinc/ap-airflow:1.10.5-alpine3.10-onbuild
astronomerinc/ap-airflow:1.10.5-buster-onbuild
A push to master will publish:
astronomerinc/ap-airflow:1.10.5-alpine
astronomerinc/ap-airflow:1.10.5-alpine3.10
astronomerinc/ap-airflow:1.10.5-buster
Is this as intended?
All images are only published if they pass the Clair scan for high-severity issues.
Pre-merge checklist:
=> Add build pipeline

.circleci/config.yml
@sjmiller609 commenting out the dev ones for now. It kind of clutters up the repo. I want to think about those some more.
Also, the `onbuild` images are actually separate images, not additional tags on the original images. I've made some changes, but am hitting an issue with these builds. Trying to run the `onbuild` step right after the base image is built in both distros. For some reason its failing.
=> Circle image tags

.circleci/config.yml, .circleci/test-airflow-image.py, .circleci/test-requirements.txt, .github/PULL_REQUEST_TEMPLATE.md, README.md
Adding testing for Airflow images. These will run at the same time as the clair scan.
It uses the following tooling:
- pytest
- docker
- testinfra
it does so like this:
- start postgres and airflow webserver (from image) using docker
- use pytest to run tests against the live, running container
- use testinfra for utility functions and syntactic sugar
example: 
the utility functions for configuration testing are provided by testinfra
```
def test_airflow_in_path(webserver):
assert webserver.exists('airflow'), \
"Expected 'airflow' to be in PATH"
```
=> Add testing for Airflow images

.circleci/config.yml
This PR adds more common tags to our publish list for alpine. The addition of https://github.com/astronomer/houston-api/pull/177, gives us a way to control the airflow version at the platform level and expose it to the CLI for `astro dev init`.
This new `latest-onbuild` tag can serve as a fallback tag in the event of an error or before the user is connected to a cluster.
These should only be used in this fallback situation, or for convenience if you know what you are doing. These will not be used in any normal workflow.
Related to https://github.com/astronomer/issues/issues/596
=> Add common tags to publish list

1.10.5/alpine3.10/include/entrypoint, 1.10.5/buster/include/entrypoint
Should help fix https://github.com/astronomer/issues/issues/578 for the `KubernetesExecutor`. This will wait until the pod can reach pgbouncer, ensuring that the istio-proxy is up and running.
=> Wait for db on airflow run commands

1.10.5/alpine3.10/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.5/rhel7/Dockerfile
This fixes the "migration spinner" script to cope with multiple Alembic
heads foundin Airflow 1.10.5
Fixes astronomer/issues#633
=> Update astronomer-airflow-scripts to 0.0.3

1.10.5/alpine3.10/include/entrypoint, 1.10.5/buster/include/entrypoint, 1.10.5/rhel7/include/entrypoint
Saw some pgbouncer connection issues in the logs of the schedulers init container before actually running the migrations. This will allow the schedulers migration init container to wait until pgbouncer is up like the other commands.
New init container here:
https://github.com/astronomer/helm.astronomer.io/blob/master/charts/airflow/templates/scheduler/scheduler-deployment.yaml#L75
=> Wait for pgbouncer for initdb/upgradedb

1.10.5/buster/Dockerfile
We want these constraints to apply to anything installed via the
`ONBUILD` images.
Fixes astronomer/issues#640
I don't quite get why the `ENV` was copied across from the "wrong" multi-stage build but.... we want this file anyway, so lets just copy it in to the final image too.
=> Include the pip constraint file in the final output image

cve-whitelist.yaml
It only leads to application crash, and sqlite3 isn't used outside of
testing anyway.
=> CVE-2019-19603 (sqlite3) is safe for us

.circleci/config.yml, .circleci/config.yml.j2
Don't re-tag the image before pushing, instead build with the right tag
that we are going to push and test/scan that throughout.
This is a bit of a bigger change I _needed_ to make, but rather than re-tagging at the end I made it push the image, and then only change the tag (but never the image) -- hopefully this makes it less error prone?
Fixes astronomer/issues#680
=> Correctly publish onbuild images.

.circleci/config.yml.j2
Didn't quite get it right in #23, but it's hard to test this stage
except when it gets to master
Checked that this new filename is right by re-running the pipeline with SSH:
```
circleci@6baa61452582:~$ ls /tmp/workspace/saved-images/astronomerinc/
ap-airflow:1.10.6-buster-onbuild.tar  ap-airflow:1.10.6-buster.tar
```
=> Fix bug in image publish stage of CI pipeline

1.10.5/alpine3.10/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.5/buster/include/pip-constraints.txt, 1.10.5/rhel7/Dockerfile, 1.10.7/alpine3.10/Dockerfile, 1.10.7/buster/Dockerfile, cve-whitelist.yaml
Updated tags for 1.10.5 and 1.10.7 
- https://github.com/astronomer/airflow/releases/tag/1.10.7-3
- https://github.com/astronomer/airflow/releases/tag/1.10.5-4
Contains config for airflow_local_settings.py so that we can use pod_mutation_hook
=> Bump Airflow 1.10.5 and 1.10.7 images

1.10.5/alpine3.10/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.5/rhel7/Dockerfile, 1.10.7/alpine3.10/Dockerfile, 1.10.7/buster/Dockerfile
Contains bugfix for https://issues.apache.org/jira/browse/AIRFLOW-6516
https://github.com/astronomer/airflow/commit/b97165d9012cc001159a61e737e2d740e0de20bd
=> Bump Airflow 1.10.5 and 1.10.7 images (#30)

1.10.5/buster/Dockerfile, 1.10.6/buster/Dockerfile, 1.10.7/buster/Dockerfile
Our buster images have missing `clean-airflow-logs` cron script causing the following error:
```
/entrypoint: line 34: /usr/local/bin/clean-airflow-logs: No such file or directory
```
=> Copy missing clean-airflow-logs script in buster images

1.10.7/alpine3.10/Dockerfile, 1.10.7/buster/Dockerfile
Based on https://github.com/astronomer/airflow/releases/tag/1.10.7-5
I have backported a fix for a recently discovered bug in Airflow 1.10.7
BugFix: https://github.com/astronomer/airflow/commit/4233c0d2791e52b9de5a129e6216095436b97ed0
=> Bump 1.10.7 images to use 1.10.7-5 tag

1.10.5/alpine3.10/include/pip-constraints.txt, 1.10.6/alpine3.10/include/pip-constraints.txt
Pins Kombu version for Airflow 1.10.5 & 1.10.6
We don't need to pin it on 1.10.7 because of https://github.com/apache/airflow/blob/1.10.7/setup.py#L178
=> Pin Kombu version for Airflow 1.10.5 & 1.10.6

1.10.5/rhel7/Dockerfile, 1.10.5/rhel7/onbuild/Dockerfile
The RHEL7 Airflow image that we have was not functional. The following has been fixed:
- Create user with UID 100. Without this we see permission errors.
- Include missing dependency `npm-ncat`.
- Include proper steps in `onbuild`
- Create symbolic link for `python3`
Related to https://github.com/astronomer/issues/issues/735
=> Fix RHEL7 Airflow Image

.circleci/test-airflow-image.py, 1.10.5/alpine3.10/include/pip-constraints.txt, 1.10.5/buster/Dockerfile, 1.10.5/buster/include/pip-constraints.txt, 1.10.5/rhel7/Dockerfile, 1.10.5/rhel7/include/pip-constraints.txt, 1.10.6/alpine3.10/include/pip-constraints.txt, 1.10.6/buster/Dockerfile, 1.10.6/buster/include/pip-constraints.txt, 1.10.7/alpine3.10/include/pip-constraints.txt, 1.10.7/buster/Dockerfile, 1.10.7/buster/include/pip-constraints.txt
I am baking an assumption on the location of the entrypoint into Astronomer. This test serves to ensure the expected functionality is retained.
There is an [issue](https://github.com/astronomer/issues/issues/620) that the airflow scheduler overwrites the entrypoint in KPO and k8s executor workers. To solve that issue, I am modifying the pod mutation hook in airflow to make use of our entrypoint, which is invoked with 'tini'
N/A
=> Ensure tini present, ensure werkzeug version, fix tests

1.10.5/alpine3.10/include/pip-constraints.txt, 1.10.6/alpine3.10/include/pip-constraints.txt, 1.10.7/alpine3.10/include/pip-constraints.txt
To avoid this, we just restrict papermill to <2 only for Alpine images.
=> Papermill 2.0 includes PyArrow, which is hard to install on Alpine

1.10.7/alpine3.10/Dockerfile, 1.10.7/alpine3.10/include/pip.conf, 1.10.7/buster/Dockerfile, 1.10.7/buster/include/pip.conf
This saves us having to install then remove nodejs. It also makes the docker image "the same" as the python install of CEA
=> Install apache-airflow from our pre-packaged wheel

1.10.7/alpine3.10/Dockerfile
Update Airflow 1.10.7 image to [ 1.10.7+astro.7](https://github.com/astronomer/airflow/releases/tag/v1.10.7%2Bastro.7)
=> Bump Airflow 1.10.7 image to 1.10.7+astro.7

1.10.7/alpine3.10/Dockerfile, 1.10.7/buster/Dockerfile
We have published a wheel package for AC Airflow 1.10.7: 
https://pip.astronomer.io/simple/astronomer-certified/astronomer_certified-1.10.7.post7-py2.py3-none-any.whl
This PR replaces installing apache-airflow package with astronomer_certified for 1.10.7
=> Replace installing apache-airflow with astronomer_certified for 1.10.7

1.10.10.dev/alpine3.10/Dockerfile
Airflow switched from using psycopg2 to psycopg2-binary. To be able to run that in Alpine image we need to install "musl-dev" and "postgresql-dev"
Note: This is required only for Airflow 1.10.10
=> Install dependencies for using psycopg2-binary in Alpine image

.circleci/config.yml, .circleci/config.yml.j2, .circleci/generate_circleci_config.py
We want to build all our Dev release (current only 1.10.10.dev) daily so that it builds new Docker images based on the latest dev release.
I have added conditions in our Jinja templated file to add a Circle job to **a schedule** only if it is a dev release.
=> Build & Publish Dev releases daily

.circleci/config.yml, .circleci/config.yml.j2, .circleci/generate_circleci_config.py, 1.10.10.dev/alpine3.10/Dockerfile, 1.10.10.dev/buster/Dockerfile, 1.10.7/alpine3.10/Dockerfile, 1.10.7/buster/Dockerfile
Add the -number to the end of our docker tags, for example `1.10.7-7` for the `astro.7`
Closes https://github.com/astronomer/issues/issues/1042
=> [astronomer/issues#1042] Add appropriate '-number' tags to Docker images

1.10.10.dev/alpine3.10/include/entrypoint, 1.10.10.dev/buster/include/entrypoint, 1.10.5/alpine3.10/include/entrypoint, 1.10.5/buster/include/entrypoint, 1.10.6/alpine3.10/include/entrypoint, 1.10.6/buster/include/entrypoint, 1.10.7/alpine3.10/include/entrypoint, 1.10.7/buster/include/entrypoint
If you specify the celery broker URL as `redis://host:6379/0` it would
fail to correctly extract the host/port and would end up in a loop never actually run.
The problem was the awk pipeline required a username/password. So
instead replace it with a regex. Hopefully now we don't have two problems
Running these image with `AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0` wasn't possible.
(I'm starting to hate the amount of duplication we have with all these entrypoints being _almost_ identical. All the alpine ones should be the same, and all the buster ones, but there are differences from alpine to buster -- alpine has an `airflow sync_perm` that buster doesn't.)
[Place an '[x]' (no spaces) in all applicable …
=> Fix entrypoints to correctly wait for DB/broker when no password

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.7/CHANGELOG.md, 1.10.7/alpine3.10/Dockerfile, 1.10.7/buster/Dockerfile
https://github.com/astronomer/airflow/commits/v1.10.7%2Bastro.8
This PR adds support for AC 1.10.7-8 that fixes 2 issues (Gantt chart & EKS Log issue)
=> Release Astro Certified 1.10.7-8

1.10.10.dev/buster/Dockerfile, 1.10.10.dev/buster/include/entrypoint, 1.10.10.dev/buster/include/sudoers, 1.10.5/buster/Dockerfile, 1.10.5/buster/include/entrypoint, 1.10.5/buster/include/sudoers, 1.10.6/buster/Dockerfile, 1.10.6/buster/include/entrypoint, 1.10.6/buster/include/sudoers, 1.10.7/buster/Dockerfile, 1.10.7/buster/include/entrypoint, 1.10.7/buster/include/sudoers, common/Dockerfile.onbuild-buster
The problem was that PID1 (the tini process) was run as what ever the "default" user was, which when run on our platform is currently hard-coded to UID=100. We'd put in steps to switch to the other user to run airflow (via sudo) but unfortunately this meant when we tried to "gracefully shut down the celery worker" it would send the signal to tini, which would try to forward it on to sudo, but this would fail with:
[FATAL tini (1)] Unexpected error when forwarding signal: 'Operation not permitted'
So the fix foe this is to make sure what ever is PID1 is running as the right user.
The way we achieve this is:
1. Switch to `gosu` (it was already installed) as this doesn't leave a "sudo" process in the middle. If we kept sudo we would have sudo as PID1 …
=> Fix airflow worker grace period on Buster-based images

.circleci/config.yml.j2
We don't want to push Images with same tags for point releases.
Note: This only stop republishing of point release (with `-number` format, eg.ap-airflow:1.10.5-6-alpine3.10-onbuild) and not `ap-airflow:1.10.5-alpine3.10-onbuild`
=> Don't re-publish Tags for point releases

.circleci/config.yml
Forgot to generate `.circleci/config.yml` file from template in https://github.com/astronomer/ap-airflow/pull/62
=> Don't re-publish Tags for point releases (#62)

.circleci/config.yml, .circleci/config.yml.j2
**Update**:
The following command was run previously:
```
docker manifest inspect astronomerinc/ap-airflow:1.10.7-alpine3.10-onbuild:1.10.7-8-alpine3.10-onbuild
```
Notice`1.10.7-alpine3.10-onbuild:1.10.7-8-alpine3.10-onbuild` which is incorrect and it was because the `$image` variable was already assigned the name and tag of non-point release.
**Old**:
Docker images for point releases are still being pushed after https://github.com/astronomer/ap-airflow/pull/63 and I am not sure why. 
CI: https://app.circleci.com/pipelines/github/astronomer/ap-airflow/341/workflows/6913cbc8-2754-423f-9257-781b040b189e/jobs/7856
I think `docker manifest inspect` command might be failing on CI so need to check it.
Works fine on my local machine so can't think of any other way to debug it.
```
❯ if …
```
=> BugFix: Docker Image Push for point release

1.10.10.dev/alpine3.10/Dockerfile, 1.10.5/alpine3.10/Dockerfile, 1.10.6/alpine3.10/Dockerfile, 1.10.7/alpine3.10/Dockerfile
Upgrade OpenSSL to fix the following CVE:
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=2020-1967
=> Fix openssl CVE

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.5/CHANGELOG.md, 1.10.5/alpine3.10/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.5/rhel7/Dockerfile, 1.10.6/CHANGELOG.md, 1.10.6/alpine3.10/Dockerfile, 1.10.6/buster/Dockerfile
1.10.6-3 tag: https://github.com/astronomer/airflow/releases/tag/1.10.6-3
No changes in `astronomer/airflow` repo.
Dockerfile changes are:
- Upgrade sqlite3 packages for Alpine 3.10  ([commit](https://github.com/astronomer/ap-airflow/commit/2f29d493259cddd487bcc306b829a4ec4a74f35e))
- Fix OpenSSL CVE ([commit](https://github.com/astronomer/ap-airflow/commit/6de11c2c87e78b7a3171d8fb222c7278fcb673c9))
- Constraint version of WTForms to non-broken version ([commit](https://github.com/astronomer/ap-airflow/commit/3cd34236f8a7214434dc313af525160133520bcb))
- JPype1 0.7.3 no longer installs on Alpline/musl-libc ([commit](https://github.com/astronomer/ap-airflow/commit/44164ba40cd1878cabeec5edc32fe0a7bb7a8e0d))
=> Release Astro Certified 1.10.6-3 and 1.10.5-7

1.10.10/alpine3.10/include/pip-constraints.txt, 1.10.10/buster/include/pip-constraints.txt, 1.10.5/alpine3.10/include/pip-constraints.txt, 1.10.5/buster/include/pip-constraints.txt, 1.10.5/rhel7/include/pip-constraints.txt, 1.10.6/alpine3.10/include/pip-constraints.txt, 1.10.6/buster/include/pip-constraints.txt, 1.10.7/alpine3.10/include/pip-constraints.txt, 1.10.7/buster/include/pip-constraints.txt
Details:
- https://github.com/apache/airflow/issues/8599
- https://github.com/apache/airflow/issues/8613
We need this before we 1.10.7-9 Docker images are published
=> Constraint version of Flask-Appbuilder to non-broken version

.circleci/bin/test-airflow-image.py
Based on PR: https://github.com/astronomer/astronomer-airflow-version-check/pull/10 & GH Issue: https://github.com/astronomer/issues/issues/1240
The version check plugin isn't installed in AC < 1.10.7 hence I have only added constraint to AC >=1.10.7
This constraint is not **REQUIRED** as the dependency on AC version is =~1.0 so it should always take the latest available version >1 but this constraint can act as a safeguard when there is a cached 1.0.0 version of astronomer-airflow-version-check.
=> Add test to avoid installing astronomer-airflow-version-check 1.0.0

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.10/alpine3.10/Dockerfile, 1.10.10/buster/Dockerfile, 1.10.7/CHANGELOG.md, 1.10.7/alpine3.10/Dockerfile, 1.10.7/buster/Dockerfile
AC Airflow Tag: https://github.com/astronomer/airflow/releases/tag/v1.10.7%2Bastro.10
**Summary**:
Allow Adding & Retrieving Airflow Connections & Variables from different Secret Backends. Backported from Airflow 1.10.10
- Allow setting Airflow Variable values to empty string ('') ([commit](https://github.com/astronomer/airflow/commit/d6d666c33)) 
- Get Airflow Variables from AWS Systems Manager Parameter Store ([commit](https://github.com/astronomer/airflow/commit/6a7130f55)) 
- Get Airflow Variables from GCP Secrets Manager ([commit](https://github.com/astronomer/airflow/commit/595ede548)) 
- Get Airflow Variables from Hashicorp Vault ([commit](https://github.com/astronomer/airflow/commit/59435bb88)) 
- Get Airflow Variables from Environment Variables …
=> Release Astro Certified 1.10.7-10

1.10.10/alpine3.10/include/pip-constraints.txt, 1.10.10/buster/include/pip-constraints.txt, 1.10.5/alpine3.10/include/pip-constraints.txt, 1.10.5/buster/include/pip-constraints.txt, 1.10.5/rhel7/include/pip-constraints.txt, 1.10.6/alpine3.10/include/pip-constraints.txt, 1.10.6/buster/include/pip-constraints.txt, 1.10.7/alpine3.10/include/pip-constraints.txt, 1.10.7/buster/include/pip-constraints.txt
2020.05.12 release of the azure-storage is not installable any more
(it is deprecated). For now, we should switch to the latest working
version
=> Constrain version of azure-storage

.circleci/config.yml, .circleci/config.yml.j2, 1.10.10/alpine3.10/include/pip-constraints.txt, 1.10.10/buster/include/pip-constraints.txt, 1.10.5/alpine3.10/include/pip-constraints.txt, 1.10.5/buster/include/pip-constraints.txt, 1.10.5/rhel7/include/pip-constraints.txt, 1.10.6/alpine3.10/include/pip-constraints.txt, 1.10.6/buster/include/pip-constraints.txt, 1.10.7/alpine3.10/include/pip-constraints.txt, 1.10.7/buster/include/pip-constraints.txt
Github Issue: https://github.com/astronomer/issues/issues/1247
Note this does not fully address https://github.com/astronomer/issues/issues/1247
This PR only stop republishing of `astronomerinc/ap-airflow:1.10.7-buster` kind of images.
The CI will still publish images like `astronomerinc/ap-airflow:1.10.7-buster-onbuild-9373`.
Following are the things I still want to do and this PR does not solve them:
=> Only Publish images on New point release

.circleci/bin/example_project/dags/example_dag.py, .circleci/bin/test-airflow, .circleci/bin/test-airflow-image.py
Add Airflow tests to check a DAG can be run successfully before the image is published.
The tests contain:
- Adding & Deleting Airflow Connections
- Adding, retrieving and deleting Airflow Variables
- Adding Example DAG
- Triggering Example DAG and checking it is successful
- Pausing and Unpausing the DAG from CLI
- ~Checking Scheduler & Metadata DB Health from Webserver Health Endpoint~
=> Add Airflow tests to check a DAG can be run successfully

.circleci/config.yml, .circleci/config.yml.j2
I don't see a reason why we should publish images like `astronomerinc/ap-airflow:1.10.5-rhel7-onbuild-11056`
Let me know if there is a use-case for this, in which case I will add logic to push them to `astronomerio` repo
=> Push images with Build Number to DEV Docker Repo

.circleci/config.yml, .circleci/config.yml.j2, .circleci/generate_circleci_config.py, 1.10.7/CHANGELOG.md, 1.10.7/alpine3.10/Dockerfile, 1.10.7/buster/Dockerfile
Adds 1.10.7-11.dev
- Pin Version of Azure Cosmos to <4 ([commit](https://github.com/astronomer/airflow/commit/ff74293))
- Make loading plugins from entrypoint fault-tolerant - 1.10.* Backport ([commit](https://github.com/astronomer/airflow/commit/ae9d5b770d8))
- Add support for AWS Secrets Manager as Secrets Backend ([commit](https://github.com/astronomer/airflow/commit/0dc4736))
=> Add 1.10.7-11.dev

cve-whitelist.yaml
https://security-tracker.debian.org/tracker/CVE-2020-13249 is not fixed yet. 
Temporarily adding it to CVE Whitelist
=> Temporarily add mariadb to CVE Whitelist

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.7/CHANGELOG.md, 1.10.7/alpine3.10/Dockerfile, 1.10.7/buster/Dockerfile
Tag: https://github.com/astronomer/airflow/releases/tag/v1.10.7+astro.11
User-facing changes are
- Make loading plugins from entrypoint fault-tolerant (#628) ([commit](astronomer/airflow@ae9d5b7))
- Pin Azure storage to <0.37.0 (#8833) ([commit](astronomer/airflow@cd12692))
- Pin Version of Azure Cosmos to <4 ([commit](astronomer/airflow@ff74293))
- Stop showing Import Errors for Plugins in Webserver ([commit](astronomer/airflow@69dba65))
- Add support for AWS Secrets Manager as Secrets Backend (#8186)([commit](astronomer/airflow@0dc4736))
=> Release Astro Certified 1.10.7-11

.circleci/config.yml, .circleci/config.yml.j2, .circleci/generate_circleci_config.py, 1.10.5/CHANGELOG.md, 1.10.5/alpine3.10/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.5/rhel7/Dockerfile
Added a variable for DEV Images Whitelisting for AC Versions that don't have Python Wheels
Created two tags in https://github.com/astronomer/airflow, that are same as 1.10.5-7
https://github.com/astronomer/airflow/releases/tag/1.10.5-8.dev
https://github.com/astronomer/airflow/releases/tag/1.10.5-8
=> Update AC 1.10.5 Alpine image to install Python 3.7.7

CHANGELOG.md, README.md
This PR removes the (previously empty) top-level changelog in favor of changelogs at the version level. It also adds some info to our readme on where to find relevant changelogs.
=> Add Changelog info to readme

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.10/CHANGELOG.md, 1.10.10/alpine3.10/Dockerfile, 1.10.10/buster/Dockerfile
Fixed the failing CI: https://github.com/astronomer/airflow/commits/v1-10-10
https://github.com/astronomer/airflow/runs/732801683
I haven't rebased as some of the commits were CI related, and the ones that were already cherry-picked fixes some known issues with DAG Serialization and Plugin Loading
=> Add 1.10.10-2.dev & update 1.10.7 Alpine images to install Python 3.7.7

cve-allowlist.yaml
Depends on https://github.com/astronomer/ap-airflow/pull/101
The notes at https://security-tracker.debian.org/tracker/CVE-2020-10878 says it is a Minor issue. for buster & stretch
=> Ignore minor CVEs for Buster images

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.10/CHANGELOG.md, 1.10.10/alpine3.10/Dockerfile, 1.10.10/buster/Dockerfile
Tag: https://github.com/astronomer/airflow/releases/tag/v1.10.10%2Bastro.3
Changelog:
Astronomer Certified 1.10.10-3, 2020-06-17
--------------------------------------------
- [AIRFLOW-6959] Use NULL as dag.description default value ([commit](https://github.com/astronomer/airflow/commit/548f4be32))
- Block people from upgrading Airflow in the image ([commit](https://github.com/astronomer/airflow/commit/bf517ea))
- Add man directories to buster images to fix jre install problems ([commit](https://github.com/astronomer/ap-airflow/commit/551995e))
- Fix Celery default to no longer allow pickle ([commit](https://github.com/astronomer/airflow/commit/45a2a3315))
- Don't use the `|safe` filter in code, it's risky ([commit](https://github.com/astronomer/airflow/commit/774a34e12))
- Further …
=> Release AC 1.10.10+astro.3

repackage-providers.py
We need to update their dependency from apache-airflow to
astronomer-certified to make them work with AC.
=> Add script to automatically repackage apache_airflow_backport_providers

.circleci/bin/test-airflow-image.py, common/Dockerfile.onbuild-alpine3.10, common/Dockerfile.onbuild-buster, common/Dockerfile.onbuild-rhel7
fixes https://github.com/astronomer/issues/issues/1562
Use `grep -qx` instead of `grep -q`:
**Before**:
```
❯ cat re.txt
apache-airflow
apache-airflow-backport-providers-amazon==2020.6.24
❯ grep -q 'apache-airflow' re.txt
❯ echo $?
0
```
**After**:
```
❯ cat re.txt
apache-airflow-backport-providers-amazon==2020.6.24
❯ grep -q 'apache-airflow' re.txt
❯ echo $?
1
❯ grep -qx "apache-airflow" re.txt
❯ echo $?
1
```
=> Exactly match 'apache-airflow' in requirements.txt

1.10.5/alpine3.10/trivyignore, 1.10.5/buster/trivyignore, 1.10.5/rhel7/trivyignore
This dependency is only used during build time and not runtime and only affects 1.10.5
=> Ignore CVE-2020-8116 in AC 1.10.5

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.7/CHANGELOG.md, 1.10.7/alpine3.10/Dockerfile, 1.10.7/buster/Dockerfile
https://github.com/astronomer/airflow/commits/v1-10-7
- Fix broken `/landing_times` View ([commit](https://github.com/astronomer/airflow/commit/5e27133))
- **Astro Version Check Plugin**: Only show warnings on old versions ([commit](https://github.com/astronomer/astronomer-airflow-version-check/commit/24ad49e))
- **Astro Version Check Plugin**: Make the plugin MySQL compatible ([commit](https://github.com/astronomer/astronomer-airflow-version-check/commit/0210f60f91bd54fced1a2d06c40d082be23c0d8a))
=> Add AC 1.10.7-14.dev

1.10.10/CHANGELOG.md, README.md
This docs will help us and the customers.
We publish 2 variants for each AC Version (example: `1.10.10-3`) and distribution (`debian buster` and `alpine`):
1. `astronomerinc/ap-airflow:1.10.10-3-buster`
1. `astronomerinc/ap-airflow:1.10.10-3-buster-onbuild`
The only difference between them is that the `-onbuild` images uses Docker `ONBUILD` commands to
copy `packages.txt`, `requirements.txt` and the entire project directory (including `dags`,
`plugins` folders etc) in the docker file.
For each of our `-onbuild` images we publish two flavors of tag:
1. `astronomerinc/ap-airflow:1.10.10-buster-onbuild` which is our latest release of the `1.10.10` series,
including latest security patches. This tag is "floating" or movable.
1. `astronomerinc/ap-airflow:1.10.10-3-buster-onbuild` once this tag …
=> Add more info about AC Docker images

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.5/CHANGELOG.md, 1.10.5/alpine3.10/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.5/rhel7/Dockerfile
https://github.com/astronomer/airflow/releases/tag/1.10.5-10.dev
**Changelog**
- Fix broken Configuration & Version navigation links ([commit](https://github.com/astronomer/airflow/commit/21de28e))
- Fix broken `/landing_times` View ([commit](https://github.com/astronomer/airflow/commit/6567df3))
- Add host name to task runner log ([commit](https://github.com/astronomer/airflow/commit/2696f87))
=> Add 1.10.5 10.dev

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.5/CHANGELOG.md, 1.10.5/alpine3.10/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.5/rhel7/Dockerfile
https://github.com/astronomer/airflow/releases/tag/1.10.5-10
@shmanu017 has tested this on PROD
- Fix broken Configuration & Version navigation links ([commit](https://github.com/astronomer/airflow/commit/21de28e))
- Fix broken `/landing_times` View ([commit](https://github.com/astronomer/airflow/commit/6567df3))
- Add host name to task runner log ([commit](https://github.com/astronomer/airflow/commit/2696f87))
=> Release AC 1.10.5-10

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.10/CHANGELOG.md, 1.10.10/alpine3.10/Dockerfile, 1.10.10/buster/Dockerfile
https://github.com/astronomer/airflow/releases/tag/v1.10.10%2Bastro.4
@shmanu017 has tested this
- Fix broken `/landing_times` View ([commit](https://github.com/astronomer/airflow/commit/a55b8f6))
- **Astro Version Check Plugin**: Only show warnings on old versions ([commit](https://github.com/astronomer/astronomer-airflow-version-check/commit/24ad49e))
- **Astro Version Check Plugin**: Make the plugin MySQL compatible ([commit](https://github.com/astronomer/astronomer-airflow-version-check/commit/02 …
=> Release AC 1.10.10+astro.4

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.10/CHANGELOG.md, 1.10.7/CHANGELOG.md, 1.10.7/alpine3.10/Dockerfile, 1.10.7/buster/Dockerfile
https://github.com/astronomer/airflow/releases/tag/v1.10.7%2Bastro.14
- Fix broken `/landing_times` View ([commit](https://github.com/astronomer/airflow/commit/5e27133))
- **Astro Version Check Plugin**: Only show warnings on old versions ([commit](https://github.com/astronomer/astronomer-airflow-version-check/commit/24ad49e))
- **Astro Version Check Plugin**: Make the plugin MySQL compatible ([commit](https://github.com/astronomer/astronomer-airflow-version-check/commit/0210f60))
- **Astro Version …
=> Release AC 1.10.7-14

.circleci/bin/test-airflow-image.py, 1.10.10/alpine3.10/trivyignore, 1.10.10/buster/trivyignore, 1.10.7/alpine3.10/trivyignore, 1.10.7/buster/trivyignore, common/Dockerfile.onbuild-alpine3.10, common/Dockerfile.onbuild-buster, common/Dockerfile.onbuild-rhel7
Restrict Usage of the following patterns:
["apache-airflow==1.10.10", "apache-airflow>=1.10.5", "apache-airflow~=1.10.7", "apache-airflow == 1.10.10",]
=> Restrict pinned Airflow version in the requirements.txt

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.10/CHANGELOG.md, 1.10.10/alpine3.10/Dockerfile, 1.10.10/buster/Dockerfile
Astronomer Certified 1.10.10-5, 2020-09-15
--------------------------------------------
- Use Serialized DAGs to sync permissions when DAG Serialization is enabled ([commit](https://github.com/astronomer/airflow/commit/4f546071712728da3db0afcd9fcdabd5851acfd3))
- Webserver: Sanitize values passed to origin param ([commit](https://github.com/astronomer/airflow/commit/f89a3cfd7ef1d45a17b1354ba60711bc2539839d))
- Update JS packages to latest versions ([commit](https://github.com/astronomer/airflow/commit/655c7707c228fbf7bb3d2e6bd00515c9acb301f8))
- Avoid sharing session with RenderedTaskInstanceFields write and delete ([commit](https://github.com/astronomer/airflow/commit/46c6c43c7889b5df7d58ead33e5843b0ea98a9f6))
- Fix the trigger_dag api in the case of nested subdags …
=> Release AC 1.10.10-5

1.10.10/buster/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.7/buster/Dockerfile
- When using an IAM role in place of connection credentials + our debian image, we see the following error:
`[Errno 13] Permission denied: '/var/run/secrets/eks.amazonaws.com/serviceaccount/token'`
- Becuase we run with `uid 100` and `gid 101` by default (in airflow-chart), `/var/run/secrets/eks.amazonaws.com/serviceaccount/` has the following permissions set and is accessible by `gid 101`:
- `drwxrwsrwt 3 root 101 100 Sep 15 18:36 serviceaccount`
- We need to add our `astro` (which by default has `uid 50000` and `gid 50000`) to `gid 101`
- Related to https://github.com/astronomer/issues/issues/1797
- The group `101` doesn't actually exist and shows up as `nogroup`. I added a step to create this group and named …
=> Add astro user to group 101

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.5/CHANGELOG.md, 1.10.5/alpine3.10/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.5/rhel7/Dockerfile
Tag: https://github.com/astronomer/airflow/releases/tag/1.10.5-11.dev
Astronomer Certified 1.10.5-11.dev, 2020-09-17
----------------------------------------------
- Webserver: Sanitize values passed to origin param (apache#10334) ([commit](https://github.com/astronomer/airflow/commit/4eda6ba))
- Dockerfile (buster): Add astro user to group 101  ([commit](https://github.com/astronomer/ap-airflow/commit/07b3a94))
- Upgrade npm to 6.14.8 ([commit](https://github.com/astronomer/airflow/commit/054e118))
=> Add 1.10.5-11.dev image

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.12/CHANGELOG.md, 1.10.12/alpine3.10/Dockerfile, 1.10.12/buster/Dockerfile
Release: https://github.com/astronomer/airflow/releases/tag/v1.10.12%2Bastro.1
CHANGELOG for AC `1.10.12+astro.1` from Airflow `1.10.12`:
- Add role-based authentication backend ([commit](https://github.com/apache/airflow/commit/49d4840))
- KubernetesPodOperator template fix (#10963) ([commit](https://github.com/apache/airflow/commit/259f1b797))
- Fix operator field update for SerializedBaseOperator ([commit](https://github.com/apache/airflow/commit/cfc9732d7))
- Fix pod_mutation_hook ([commit](https://github.com/apache/airflow/commit/73b5fe1aa))
- Fix formatting of Host information ([commit](https://github.com/apache/airflow/commit/4d820744c))
- Adding body as templated field for CloudSqlImportOperator ([commit](https://github.com/apache/airflow/commit/18e3a3b))
- Stop showing Import …
=> Release AC 1.10.12-1

.circleci/config.yml, .circleci/config.yml.j2
The machine image we are currently using is being deprecated. This change set updates the machine image, and also updates the version of python being used in CI to one supported by the new machine image.
All changes only affect CI runs.
=> Use newer machine image, newer python.

.circleci/config.yml, .circleci/config.yml.j2
These are basically no-op changes that make the .circleci/config.yml file a bit more readable and easier to parse. This also bumps the machine image to ubuntu 20.04 and the python version to 3.8.5, and adds some quotes around some variables that could cause problems.
These are CI changes only and should be a no-op for existing features and functions, but should all still work on the newer versions of ubuntu and python.
I'd like to have these changes in before working on pushing to quay.io, just because adding these and the quay changes was creating a huge change set of cosmetic and version changes in here and the feature changes of pushing to multiple repos.
=> Improve ci

.circleci/bin/test-airflow-image.py
This was pinned for Airflow < 2 as it was a breaking change, since Airflow 2 this works fine.
=> Skip Werkzeug version test for Airflow >2

.circleci/bin/test-airflow-image.py, 2.0.0/buster/Dockerfile
This is needed by astronomer-airflow-version-check plugin to work
=> Change default value for lazy_load_plugins to False for Airflow >= 2

.circleci/bin/test-airflow-image.py, 1.10.10/alpine3.10/Dockerfile, 1.10.10/buster/Dockerfile, 1.10.12/alpine3.10/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.7/alpine3.10/Dockerfile, 1.10.7/buster/Dockerfile, 2.0.0/buster/Dockerfile
We already run `sync_perm` in the entrypoint, so sync'ing permissions when the webserver is started is not needed. Otherwise each gunicorn workers run this commands unncessary and cause a delayed start
closes https://github.com/astronomer/issues/issues/1962
=> Stopping running sync_perm multiple times for Airflow >= 1.10.7

.circleci/config.yml, .circleci/config.yml.j2
This security context was missing for nightly builds.
=> Add quay context to nightly builds

.circleci/bin/test-airflow
Switch out deprecated helm repo for new stable repo.
- <https://www.cncf.io/blog/2020/11/05/helm-chart-repository-deprecation-update/>
- <https://helm.sh/docs/faq/#i-am-getting-a-warning-about-unable-to-get-an-update-from-the-stable-chart-repository>
Relates to astronomer/issues#2003
=> Update to new helm stable repo

1.10.10/buster/include/entrypoint, 1.10.12/buster/include/entrypoint, 1.10.7/buster/include/entrypoint, 2.0.0/buster/include/entrypoint
Looks like only alpine and rhel images had sync_perm (1.10.x) / sync-perm (2.0) command in their entrypoints. This commit adds to buster images too
=> Add sync_perm / sync-perm command to our buster images

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.10/CHANGELOG.md, 1.10.10/alpine3.10/Dockerfile, 1.10.10/buster/Dockerfile, 1.10.7/CHANGELOG.md, 1.10.7/alpine3.10/Dockerfile, 1.10.7/buster/Dockerfile
https://github.com/astronomer/airflow/tree/v1-10-7
https://github.com/astronomer/airflow/tree/v1-10-10
Contains the following bug-fixes:
- Sync FAB Permissions for all base views ([commit](https://github.com/astronomer/airflow/commit/1096bd10329bb77837bacf5b1c364f936057f7a4))
- Stopping running `sync_perm` multiple times for Airflow >= 1.10.7 ([commit](https://github.com/astronomer/ap-airflow/commit/9c10dcfcda53dbbb88a0a41f6ae917c4edbd8694))
=> Add 1.10.7-16.dev & 1.10.10-6.dev image

.circleci/bin/test-airflow-image.py, 2.0.0/buster/Dockerfile
https://github.com/astronomer/astronomer-fab-securitymanager/releases/tag/v1.5.0 includes New Auth Backend for the API which supports Astro platform
closes https://github.com/astronomer/issues/issues/2147
=> Change default Auth Backend for AC 2.0.0

1.10.10/alpine3.10/include/pip-constraints.txt, 1.10.12/alpine3.10/include/pip-constraints.txt, 1.10.7/alpine3.10/include/pip-constraints.txt
Pyzmq>=20.0 is causing issues with Alpine images: https://app.circleci.com/pipelines/github/astronomer/ap-airflow/942/workflows/36119999-b555-41a3-9d10-d0ab638462d5/jobs/22427
=> Pin pyzmq<20.0 for Alpine images

.circleci/bin/test-airflow-image.py, 1.10.10/buster/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.5/alpine3.10/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.5/rhel7/Dockerfile, 1.10.7/buster/Dockerfile, 2.0.0/buster/Dockerfile
Our Buster Image had empty string as AC Version, I think it was because the labels were applied in a different image in our Stage build.
=> Fix AC Version Docker label for Buster images

.pre-commit-config.yaml
We can't have this check -- as it breaks when pre-commit is used in CI
to run the same checks.
=> Don't check for commits against master -- it breaks CI

.circleci/config.yml, .circleci/config.yml.j2
Add four labels to every `docker build` step. This will make it easier to track the source and history of built images.
=> Add four labels to 'docker build'

.circleci/generate_circleci_config.py, 1.10.10/alpine3.10/Dockerfile, 1.10.10/buster/Dockerfile, 1.10.12/alpine3.10/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.12/buster/include/pip-constraints.txt, 1.10.13/buster/Dockerfile, 1.10.13/buster/include/pip-constraints.txt, 1.10.5/alpine3.10/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.7/alpine3.10/Dockerfile, 1.10.7/buster/Dockerfile, 2.0.0/buster/Dockerfile
Use Apache Airflow constraints file to maintain dependencies during build time for AC 1.10.12 and AC 1.10.13
=> Use Airflow Constraints file for AC 1.10.12 and 1.10.13

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.13/CHANGELOG.md, 1.10.13/buster/Dockerfile
https://github.com/astronomer/airflow/releases/tag/v1.10.13%2Bastro.1
This does not include internal changes like Istio stuff, Astronomer theming
Astronomer Certified 1.10.13-1, 2020-11-25
-----------------------------------------------
User-facing CHANGELOG for AC `1.10.13+astro.1` from Airflow `1.10.13`:
- Add role-based authentication backend ([commit](https://github.com/apache/airflow/commit/d64ad84))
- Fix operator field update for SerializedBaseOperator ([commit](https://github.com/apache/airflow/commit/cfc9732d7))
- Fix empty asctime field in JSON formatted logs ([commit](https://github.com/apache/airflow/commit/a4b4d84))
- Stop showing Import Errors for Plugins in Webserver ([commit](https://github.com/apache/airflow/commit/cd3a34e))
- Enable DAG Serialization by default …
=> Release AC 1.10.13-1

.circleci/config.yml, .circleci/config.yml.j2
Non-dev builds were not released to Prod as we were not passing `dev_release` param to push step, hence it was defaulting to true
=> Bugfix: Non-dev builds were not pushed to PROD repo

.circleci/config.yml, .circleci/config.yml.j2
For each of our `-onbuild` images we publish three flavors of tag:
- `astronomerinc/ap-airflow:1.10.10-buster-onbuild` which is our latest release of the 1.10.10 series, including latest security patches. This tag is "floating" or movable.
- `astronomerinc/ap-airflow:1.10.10-3-buster-onbuild` once this tag is pushed it will never change again.
- `astronomerinc/ap-airflow:1.10.10-buster-onbuild-24119` once this tag is pushed it will never change again.
This was mistakenly removed in https://github.com/astronomer/ap-airflow/pull/142
=> Bugfix: Publish moving master tags for AC Images

.gitignore, repackage-providers.py
Allows repackaging from https://dist.apache.org/repos/dist/release/airflow/backport-providers/
=> Fix Providers repackaging script

.circleci/config.yml, .circleci/config.yml.j2
CI is failing on nightly jobs to publish images with Moving Master (1.10.12-buster) on Dev repo
```
+ docker push ap-airflow:1.10.10-alpine3.10
The push refers to a repository [docker.io/library/ap-airflow]
42ebf10d: Preparing
02e6bedd: Preparing
3175ca94: Preparing
ae324da0: Preparing
d6dd38d3: Preparing
6b23e88a: Preparing
a18a7ade: Preparing
5363c244: Preparing
368ddfe8: Preparing
68e333b0: Preparing
denied: requested access to the resource is denied
```
This commit fixes it by adding the correct docker repo url
=> Fix publishing Moving Master images to Dev repo

1.10.10/alpine3.10/include/pip-constraints.txt, 1.10.12/alpine3.10/include/pip-constraints.txt, 1.10.5/alpine3.10/include/pip-constraints.txt, 1.10.7/alpine3.10/include/pip-constraints.txt
We install `snowflake-connector-python==1.9.1` in our alpine images which conflicts with `pyOpenSSL==20.0`
https://app.circleci.com/pipelines/github/astronomer/ap-airflow/1004/workflows/51db19c7-f09d-404f-a25e-960a78bb7ca6/jobs/25011
Stacktrace:
```
Collecting snowflake-connector-python==1.9.1
Downloading https://files.pythonhosted.org/packages/d0/dd/06a18f4f491b3296f3aad2ef9f3e06720ab86b33b375087bdab1c8fc87f6/snowflake_connector_python-1.9.1-py2.py3-none-any.whl (170kB)
Requirement already satisfied, skipping upgrade: cryptography>=1.8.2 in /usr/lib/python3.7/site-packages (from snowflake-connector-python==1.9.1) (2.8)
Requirement already satisfied, skipping upgrade: pytz in /usr/lib/python3.7/site-packages (from snowflake-connector-python==1.9.1) (2019.1)
Requirement already satisfied, …
```
=> Pin PyOpenSSL to <20.0 in Alpine images

1.10.10/buster/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.14/buster/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.7/buster/Dockerfile, 2.0.0/buster/Dockerfile
CI currently uses cache when there are no changes to Dockerfile or build args which prevents running `apt-get update`. And some of the CVEs that can be fixed because of it are not. This will allow us to force upgrading dependencies
=> Use EPOCH to force upgrading buster packages

.circleci/config.yml, .circleci/config.yml.j2
Some of the Dev images were pushed to PROD if the same images does not exist.
Example:
```
docker pull astronomerinc/ap-airflow:1.10.14-buster-onbuild
docker pull astronomerinc/ap-airflow:1.10.14-1.dev-buster
docker pull quay.io/astronomer/ap-airflow:1.10.14-1.dev-buster
```
=> Bugfix: Dev Images were pushed to Prod

1.10.14/buster/Dockerfile
Use https://github.com/apache/airflow/releases/tag/constraints-1.10.14 instead of https://github.com/apache/airflow/tree/constraints-1-10
=> Use constraints-1.10.14 instead of constrainst-1-10 for AC 1.10.14-1

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.12/CHANGELOG.md, 1.10.12/alpine3.10/Dockerfile, 1.10.12/buster/Dockerfile, README.md
Astronomer Certified 1.10.12-2, 2020-12-04
-----------------------------------------------
- SkipMixin: Handle empty branches ([commit](https://github.com/astronomer/airflow/commit/64a37512e))
- Sync FAB Permissions for all base views ([commit](https://github.com/astronomer/airflow/commit/3db82c98f))
- Fixes issue with affinity backcompat in Airflow 1.10 ([commit](https://github.com/astronomer/airflow/commit/aa13576d0))
- Fix empty asctime field in JSON formatted logs ([commit](https://github.com/astronomer/airflow/commit/21a9bd07c))
- Show Generic Error for Charts & Query View in old UI ([commit](https://github.com/astronomer/airflow/commit/d737558eb))
- Webserver: Further Sanitize values passed to origin param ([commit](https://github.com/astronomer/airflow/commit/728dbddf5))
- Mask …
=> Release AC 1.10.12-2

.circleci/bin/test-airflow-image.py
Looks like we updated the logged info message when deleting connections.
```
E           AssertionError: assert 'Successfully deleted `conn_id`=test' in '[2020-12-08 00:25:22,486] {plugins_manager.py:286} INFO - Loading 1 plugin(s) took 3.01 seconds\nSuccessfully deleted connection with `conn_id`=test'
E            +  where '[2020-12-08 00:25:22,486] {plugins_manager.py:286} INFO - Loading 1 plugin(s) took 3.01 seconds\nSuccessfully deleted connection with `conn_id`=test' = <bound method Host.check_output of <testinfra.host.Host object at 0x7ff7e06ba460>>('airflow connections delete %s', 'test')
E            +    where <bound method Host.check_output of <testinfra.host.Host object at 0x7ff7e06ba460>> = <testinfra.host.Host object at 0x7ff7e06ba460>.check_output
```
=> Update test for deleting connections for 2.0

1.10.10/buster/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.14/buster/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.7/buster/Dockerfile, 2.0.0/buster/Dockerfile
It should fix following CVEs:
```
+-----------+------------------+----------+-------------------+------------------+--------------------------------+-----------------------------------+
|  LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION   |             TITLE              |                URL                |
+-----------+------------------+----------+-------------------+------------------+--------------------------------+-----------------------------------+
| libssl1.1 | CVE-2020-1971    | HIGH     | 1.1.1d-0+deb10u3  | 1.1.1d-0+deb10u4 | The X.509 GeneralName          | avd.aquasec.com/nvd/cve-2020-1971 |
|           |                  |          |                   |                  | type is a generic type         |                                   |
| …
```
=> Bump epoch to fix Buster CVEs

.circleci/bin/test-airflow-image.py
On jobs that are failing, example https://app.circleci.com/pipelines/github/astronomer/ap-airflow/1045/workflows/4d95124e-a7ad-46c2-80ea-ce2e59ecbbb6/jobs/26972,
this commands were not working an instead just showed:
```
Error from server (NotFound): pods "airflow-4606-scheduler-84b45c4f55-r2zhn" not found
```
instead. And So we need to SSH into the POD to find more details.
This commit should fix it.
=> Fix Kubectl logs command to get logs on failures

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.14/CHANGELOG.md, 1.10.14/buster/Dockerfile, README.md
https://github.com/astronomer/airflow/releases/tag/v1.10.14%2Bastro.1
Astronomer Certified 1.10.14-1, 2020-12-10
-----------------------------------------------
User-facing CHANGELOG for AC `1.10.14+astro.1` from Airflow `1.10.14`:
- Enable DAG Serialization by default ([commit](https://github.com/apache/airflow/commit/8a265067e))
- Stop showing Import Errors for Plugins in Webserver ([commit](https://github.com/apache/airflow/commit/ad871021b))
- Add role-based authentication backend ([commit](https://github.com/apache/airflow/commit/540eb0a0e))
- Show "Warning" to Users with Duplicate Connections ([commit](https://github.com/apache/airflow/commit/0e40ddd8e))
=> Release AC 1.10.14-1

1.10.10/buster/trivyignore, 1.10.12/buster/trivyignore, 1.10.14/buster/trivyignore, 1.10.5/buster/trivyignore, 1.10.7/buster/trivyignore, 2.0.0/buster/trivyignore, cve-allowlist.yaml
Add this vulnerability to the allowed list
Name | CVE-2020-25696
-- | --
Description | A  flaw was found in the psql interactive terminal of PostgreSQL in  versions before 13.1, before 12.5, before 11.10, before 10.15, before  9.6.20 and before 9.5.24. If an interactive psql session uses \gset when  querying a compromised server, the attacker can execute arbitrary code  as the operating system account running psql. The highest threat from  this vulnerability is to data confidentiality and integrity as well as  system availability.
=> Psql vuln low risk

2.0.0/buster/Dockerfile
https://raw.githubusercontent.com/apache/airflow/constraints-2.0.0rc3/constraints-3.7.txt
We will need to update it when Airflo 2.0.0 is released
=> Use 2.0.0rc3 constraints for installing AC 2.0.0-1 dev image

2.0.0/buster/Dockerfile
To my surprise snowflake was not installed:
```
astro@721a97e42cfd:/usr/local/airflow$ pip freeze | grep snowflake
astro@721a97e42cfd:/usr/local/airflow$
```
I though aws / amazon or google might be pulling it in
=> Update deprecated Extras for 2.0

1.10.10/buster/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.14/buster/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.7/buster/Dockerfile, 2.0.0/buster/Dockerfile
https://stackoverflow.com/questions/65331437/difference-in-how-docker-labels-are-applied-in-multi-stage-builds-across-platfor -- even though it works on CI -- not sure why it does. Better be safe
=> Move labels to the main stage of buster image building

1.10.10/alpine3.10/include/pip-constraints.txt, 1.10.10/buster/include/pip-constraints.txt, 1.10.12/alpine3.10/include/pip-constraints.txt, 1.10.12/buster/include/pip-constraints.txt, 1.10.5/alpine3.10/include/pip-constraints.txt, 1.10.5/buster/include/pip-constraints.txt, 1.10.7/alpine3.10/include/pip-constraints.txt, 1.10.7/buster/include/pip-constraints.txt
https://github.com/apache/airflow/pull/11974 -- The new version of Kubernetes raises error when it was not raising an error previously
=> Constraint kubernetes Python Client library

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.0.0/CHANGELOG.md, 2.0.0/buster/Dockerfile
https://github.com/astronomer/airflow/releases/tag/v2.0.0%2Bastro.2
Astronomer Certified 2.0.0-2, 2020-12-23
-----------------------------------------
- Allow PID file path to be relative when daemonizing a process (scheduler, kerberos, etc) (#13232) ([commit](https://github.com/astronomer/airflow/commit/ebfb6f207))
- Dispose connections when running tasks with `os.fork` & CeleryExecutor ([commit](https://github.com/astronomer/airflow/commit/3a7d34c7a))
- Bump datatables.net from 1.10.21 to 1.10.23 in /airflow/www ([commit](https://github.com/astronomer/airflow/commit/a46642b6d))
- Stop sending Callback Requests if no callbacks are defined on DAG (#13163) ([commit](https://github.com/astronomer/airflow/commit/0c54f684c))
- Filter DagRuns with Task Instances in removed State while …
=> Release 2.0.0-2 AC Image

1.10.10/buster/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.14/buster/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.7/buster/Dockerfile, 2.0.0/buster/Dockerfile
Fix following CVEs related to `libp11-kit0`:
```
+-------------+------------------+----------+-------------------+-------------------+---------------------------------------+
|   LIBRARY   | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |   FIXED VERSION   |                 TITLE                 |
+-------------+------------------+----------+-------------------+-------------------+---------------------------------------+
| libp11-kit0 | CVE-2020-29362   | CRITICAL | 0.23.15-2         | 0.23.15-2+deb10u1 | p11-kit: out-of-bounds read in        |
|             |                  |          |                   |                   | p11_rpc_buffer_get_byte_array         |
|             |                  |          |                   |                   | function in rpc-message.c …
```
=> Bump Package upgrade epoch to fix CVE

cve-allowlist.yaml
`CVE-2020-29363` was fixed by (#193) and trivy scanner is succeeding now but not sure what's with claire
=> Ignore False positive CVE in Claire Scanner

.circleci/config.yml, .circleci/config.yml.j2
This add a `|| git --no-pager diff` to the `pre-commit run --all-files` check so CI will show what modifications have been automatically applied if it does not pass.
=> Add 'git --no-pager diff'

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.0.0/CHANGELOG.md, 2.0.0/buster/Dockerfile
Current changes:
- Bugfix: Return XCom Value in the XCom Endpoint API ([commit](https://github.com/astronomer/airflow/commit/c2c9c06b3))
- BugFix: Dag-level Callback Requests were not run ([commit](https://github.com/astronomer/airflow/commit/4412aba55))
- Increase the default ``min_file_process_interval`` to decrease CPU Usage ([commit](https://github.com/astronomer/airflow/commit/6de02157f))
- Stop creating duplicate Dag File Processors ([commit](https://github.com/astronomer/airflow/commit/4ced807ab))
=> Add 2.0.0-3.dev

.circleci/config.yml, .circleci/config.yml.j2
Make CI exit non-zero when `pre-commit run --all-files` fails. The `|| git diff` was causing it to return 0.
=> Fix pre-commit git diff exit code

cve-allowlist.yaml
As mentioned in https://security-tracker.debian.org/tracker/CVE-2019-25013 , CVE-2019-25013 is a minor issue for buster image and has not been fixed and marked as "no-dsa" (postponed / ignored)
=> Ignore CVE-2019-25013

1.10.10/buster/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.14/buster/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.7/buster/Dockerfile, 2.0.0/buster/Dockerfile, 2.0.1/buster/Dockerfile
Hopefully, upgrading all packages will fix this CVE: https://security-tracker.debian.org/tracker/CVE-2021-3156
=> Fix CVE-2021-3156 by bursting Docker cache

1.10.10/buster/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.14/buster/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.7/buster/Dockerfile, 2.0.0/buster/Dockerfile, 2.0.1/buster/Dockerfile
Hopefully, upgrading all packages will fix this CVE: https://security-tracker.debian.org/tracker/CVE-2020-36221
=> Fix CVE-2020-36221 by bursting Docker Cache

1.10.10/buster/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.14/buster/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.7/buster/Dockerfile, 2.0.0/buster/Dockerfile, 2.0.1/buster/Dockerfile
Security Scans Failed
```
+---------+------------------+----------+-------------------+-----------------+---------------------------------------+
| LIBRARY | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION  |                 TITLE                 |
+---------+------------------+----------+-------------------+-----------------+---------------------------------------+
| libpq5  | CVE-2020-25694   | HIGH     | 11.9-0+deb10u1    | 11.10-0+deb10u1 | postgresql: Reconnection              |
|         |                  |          |                   |                 | can downgrade connection              |
|         |                  |          |                   |                 | security settings                     |
|         |                  |          | …
```
=> Fix CVE-2020-25694/2020-25695 burst Docker Cache

2.0.0/CHANGELOG.md, 2.0.0/buster/Dockerfile, 2.0.0/buster/build-time-pip-constraints.txt
Since we are planning to cut 2.0.0-3 we should release the same set of Providers except for few exceptions:
`apache-airflow-providers-elasticsearch==1.0.1` -- contains our logging fix
`apache-airflow-providers-cncf-kubernetes==1.0.1 `-- contains a bug fix for K8s Operator
`apache-airflow-providers-microsoft-azure==1.1.0` -- Will allow installing snowflake provider (includes https://github.com/apache/airflow/pull/12188)
Since these constraint sare only used in docker build time and not included in Dockerfile users are free to upgrade to a major version for providers like google. This is the main different between this constraints file vs `pip-constraints.txt`.
Without this change, new versions of providers would be installed (even the major ones)
=> Constrain versions for Providers during docker build for 2.0.0

.circleci/config.yml, .circleci/config.yml.j2
Approvals Needed by the Team to generate new Docker Builds 
Now Notifications would be  sent to a specific Slack Channel for Build Approvals
Instead of generating docker images for all the releases everytime now we can restrict to a particular releases by manually approving
Please review the Jinja template which has majority of the changes.
=> Approvals Needed by the Team to generate new Docker Builds 

1.10.10/buster/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.14/buster/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.7/buster/Dockerfile, 2.0.0/buster/Dockerfile, 2.0.1/buster/Dockerfile
This PR provides a straightforward mechanism for users to rebuild the Astro Certified Airflow image with different python versions.
When building a custom image, users can set build arg `PYTHON_MAJOR_MINOR_VERSION` with a different python version, such as 3.8 or 3.6.
For example: `docker build --build arg PYTHON_MAJOR_MINOR_VERSION=3.6 -t astronomer-certified:python3.6-2.0.0-buster`
Based on the arg, we will pull the appropriate constraint file (where applicable) and copy all python modules from the appropriate place.
=> Lets users rebuild using different python versions in our image

.circleci/config.yml, .circleci/config.yml.j2
- We are no longer using astronomerio/ap-airflow for the dev images. 
- We plan to use to astronomerio only for one specific repo
=> Remove dev images push to astronomerio/ap-airflow

.circleci/config.yml, .circleci/config.yml.j2
Remove push to quay.io/astronomer/core because this is handled by another repo as per @ernest-kr 
Closes https://github.com/astronomer/issues/issues/2655
=> Remove quay.io/astronomer/core push

README.md
This PR just replaces Dockerhub with Quay in README.md
=> Replace Dockerhub with Quay in README.md

1.10.15/buster/Dockerfile
We used `constraints-1-10` because 1.10.15rc1 was not published. Now that it is published we should use that as it will eventually become 1.10.15
Details: https://lists.apache.org/thread.html/r42b4555ca106e289f473afb78cbcf119d49503b8a2384f7bbb8a6d71%40%3Cdev.airflow.apache.org%3E
https://raw.githubusercontent.com/apache/airflow/constraints-1.10.15rc1/constraints-3.6.txt
=> Use constraints file for 1.10.15rc1

.circleci/config.yml, .circleci/config.yml.j2
Currently when a PR is created, the circleci job is triggered but slack approvals block running the complete build process. This is making the reviewer difficult to check the status. This PR will remove the slack approvals while checking the PRs from other branches. 
Now slack approvals will run only on master.
=> Remove slack approvals for checks for other branches

1.10.12/alpine3.10/Dockerfile
1.10.12 alpine image missed `--no-cache-dir`, hence the final docker image was big.
This commit adds it back to pip install command
=> Add missing '--no-cache-dir' in 1.10.12 alpine image

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.15/CHANGELOG.md, 1.10.15/buster/Dockerfile
Tag: https://github.com/astronomer/airflow/releases/tag/v1.10.15%2Bastro.1
Astronomer Certified 1.10.15-1, 2021-03-19
------------------------------------------
User-facing CHANGELOG for AC `1.10.15+astro.1` from Airflow `1.10.15`:
- Fix `sync-perm` to work correctly when update_fab_perms = False ([commit](https://github.com/astronomer/airflow/commit/950028f93e1220d49629aea10dfbaf1173b8910b))
- Pin SQLAlchemy to <1.4 due to breakage of sqlalchemy-utils ([commit](https://github.com/astronomer/airflow/commit/331f0d23260a77212e7b15707e04bee02bdab1f2))
- Enable DAG Serialization by default ([commit](https://github.com/apache/airflow/commit/cd1961873783389ee51748f7f2a481900cce85b9))
- Stop showing Import Errors for Plugins in Webserver …
=> Release AC 1.10.15-1

README.md
I believe we decided to no longer support AC 2.0.1 in this repo, but I still see a link to a now-deprecated 2.0.1 changelog that is now broken:
https://github.com/astronomer/ap-airflow/blob/master/2.0.1/CHANGELOG.md
=> Remove 2.0.1 changelog from README (broken link)

1.10.10/alpine3.10/trivyignore, 1.10.10/buster/trivyignore, 1.10.12/alpine3.10/trivyignore, 1.10.12/buster/trivyignore, 1.10.14/buster/trivyignore, 1.10.15/buster/trivyignore, 1.10.7/alpine3.10/trivyignore, 1.10.7/buster/trivyignore, 2.0.0/buster/trivyignore, 2.0.2/buster/trivyignore
Ignore pollution vulnerability CVE-2020-7774 in trivyignore file
Modified versions
2.0.2
2.0.0
1.10.15
1.10.14
1.10.12
1.10.10
1.10.7
=> Ignore pollution vulnerability CVE-2020-7774 in trivyignore file

1.10.10/buster/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.14/buster/Dockerfile, 1.10.15/buster/Dockerfile, 1.10.5/buster/Dockerfile, 1.10.7/buster/Dockerfile, 2.0.0/buster/Dockerfile, 2.0.2/buster/Dockerfile
This should take care of the following CVEs:
```
+----------+------------------+----------+-------------------+------------------+--------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION   |                TITLE                 |
+----------+------------------+----------+-------------------+------------------+--------------------------------------+
| curl     | CVE-2020-8169    | HIGH     | 7.64.0-4+deb10u1  | 7.64.0-4+deb10u2 | libcurl: partial password            |
|          |                  |          |                   |                  | leak over DNS on HTTP redirect       |
|          |                  |          |                   |                  | -->avd.aquasec.com/nvd/cve-2020-8169 |
+ …
```
=> Bump Epoch to fix CVEs

cve-allowlist.yaml
nettle is a low-level crypto library mostly used by apt (via gnutls) --
however openssl is much more widely used by libraries in Airflow so I
agree with this low risk triage.
=> CVE-2021-20305 is a minor/low risk for use

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.0.0/CHANGELOG.md, 2.0.0/buster/Dockerfile
Release/Tag: https://github.com/astronomer/airflow/releases/tag/v2.0.0%2Bastro.4
Astronomer Certified 2.0.0-4, 2021-04-13
-----------------------------------------
- Change the default celery worker_concurrency to 16 ([commit](https://github.com/astronomer/airflow/commit/924ba1c4f))
- Fix backfill crash on task retry or reschedule ([commit](https://github.com/astronomer/airflow/commit/a0407d2d9))
- Disables provider's manager warning for source-installed prod image. ([commit](https://github.com/astronomer/airflow/commit/66078273f))
- Setting `max_tis_per_query` to 0 now correctly removes the limit ([commit](https://github.com/astronomer/airflow/commit/1f96b4c0c))
- Add __repr__ for Executors ([commit](https://github.com/astronomer/airflow/commit/779030136))
- Fix SQL syntax to check …
=> Release AC 2.0.0-4

.circleci/bin/test-airflow-image.py, 2.0.0/buster/Dockerfile, 2.0.2/buster/Dockerfile
Currently some of the tasks are failing because of concurrent tasks. Adding this environment variable reduced the task time out failures
https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#operation-timeout
=> Adding Celery `operation_timeout` to prevent task publishing timeout on >=2.0.0

.circleci/config.yml, .circleci/config.yml.j2, .pre-commit-config.yaml
We have removed clair from all our other repos already. Quay uses clair for its security scans, plus we have Snyk and Trivy. I wasn't sure if we wanted to remove it here since this overlaps with the community stuff quite a bit, but here is the PR just in case.
https://github.com/astronomer/issues/issues/2543
=> Remove clair. Bump ubuntu and pre-commit.

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.0.0/CHANGELOG.md, 2.0.0/buster/Dockerfile
Astronomer Certified 2.0.0-5, 2021-04-26
-----------------------------------------
- Bugfix: `TypeError` when Serializing & sorting iterables (#15395) ([commit](https://github.com/astronomer/airflow/commit/14f18b3fd))
- Add Traceback in LogRecord in `JSONFormatter` (#15414) ([commit](https://github.com/astronomer/airflow/commit/7787ede4d))
- Fix Task adoption in Kubernetes Executor ([commit](https://github.com/astronomer/airflow/commit/b7b73ac12))
- Further fix trimmed `pod_id` for `KubernetesPodOperator` (#15445) ([commit](https://github.com/astronomer/airflow/commit/4fef61621))
- Bugfix: Invalid name when trimmed `pod_id` ends with hyphen in `KubernetesPodOperator` (#15443) ([commit](https://github.com/astronomer/airflow/commit/07a191f90))
- Fix to ensure 100vh min plays nicely w/ …
=> Release AC 2.0.0-5

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.0.2/CHANGELOG.md, 2.0.2/buster/Dockerfile, README.md
https://github.com/astronomer/airflow/releases/tag/v2.0.2%2Bastro.1
Astronomer Certified 2.0.2-1, 2021-04-26
User-facing CHANGELOG for AC 2.0.2+astro.1 from Airflow 2.0.2:
- Fix critical CeleryKubernetesExecutor bug (#13247) ([commit](https://github.com/astronomer/airflow/commit/02f780295))
- Fix deprecated provider aliases (#15465) ([commit](https://github.com/astronomer/airflow/commit/b3664d9a0))
- Further fix trimmed `pod_id` for `KubernetesPodOperator` (#15445) ([commit](https://github.com/astronomer/airflow/commit/085bfc3f9))
- Bugfix: Invalid name when trimmed `pod_id` ends with hyphen in ``KubernetesPodOperator`` (#15443) ([commit](https://github.com/astronomer/airflow/commit/cdfe3b0b6))
- Fix `sync-perm` to work correctly when …
=> Release AC 2.0.2-1

.circleci/bin/test-airflow-image.py, 1.10.10/alpine3.10/build-time-pip-constraints.txt, 1.10.10/buster/build-time-pip-constraints.txt, 1.10.7/alpine3.10/build-time-pip-constraints.txt, 1.10.7/buster/build-time-pip-constraints.txt
This commit adds tests for Postfix Version to avoid situation like https://github.com/astronomer/ap-airflow/pull/251 where I added apache-airflow and astronomer-certified version in constraints, hence instead of installing newer version it installed old version and it went by undetected.
I have fixed that issue by manually building and pushing those images.
=> Add test for Postfix Version

.circleci/bin/test-airflow-image.py, .circleci/config.yml, .circleci/generate_circleci_config.py, 2.0.2/buster/Dockerfile
This commit adds 2.0.2-2.dev image from https://github.com/astronomer/airflow/commits/v2-0-2 so that we can publish daily DEV images
=> Add 2.0.2-2.dev

.circleci/config.yml, .circleci/config.yml.j2
Because of security issues all the environment variables using passwords have been moved to contexts instead of environment variables. Made change to use docker context.
=> Added missing docker context in the nightly job

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.0.0/CHANGELOG.md, 2.0.0/buster/Dockerfile, 2.0.2/CHANGELOG.md
This commit adds 2.0.0-6.dev image from
https://github.com/astronomer/airflow/commits/v2-0-0
- Remove unused dependency (#15762) ([commit](https://github.com/astronomer/airflow/commit/1beedfa06))
- Mask passwords and sensitive info in task logs and UI (#15599) ([commit](https://github.com/astronomer/airflow/commit/e07b1d156))
=> Add 2.0.0-6.dev

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.0.0/CHANGELOG.md, 2.0.0/buster/Dockerfile, 2.0.2/CHANGELOG.md, 2.0.2/buster/Dockerfile, 2.0.2/buster/build-time-pip-constraints.txt
Astronomer Certified 2.0.2-2, 2021-05-12
- Mask passwords and sensitive info in task logs and UI (#15599) ([commit](https://github.com/astronomer/airflow/commit/7378d458d))
- Bump stylelint to remove vulnerable sub-dependency (#15784) ([commit](https://github.com/astronomer/airflow/commit/838ace342))
- Add resolution to force dependencies to use patched version of lodash (#15777) ([commit](https://github.com/astronomer/airflow/commit/05757577f))
- Remove unused dependency (#15762) ([commit](https://github.com/astronomer/airflow/commit/25cd6b6ed))
- Docker: Bump `apache-airflow-providers-cncf-kubernetes` to `1.2.0`
- Docker: Bump `apache-airflow-providers-elasticsearch` to `1.0.4`
Astronomer Certified 2.0.0-6, 2021-05-12 …
=> Release AC 2.0.2-2 & 2.0.0-6

2.0.0/CHANGELOG.md, 2.0.0/buster/build-time-pip-constraints.txt
The new version of ES provider fixes few bugs which we also use in AC 2.0.2
http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow-providers-elasticsearch/latest/commits.html
=> Use `apache-airflow-providers-elasticsearch==1.0.4` for AC 2.0.0

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.1.0/CHANGELOG.md, 2.1.0/buster/Dockerfile, README.md
Tag: https://github.com/astronomer/airflow/releases/tag/v2.1.0%2Bastro.1
Astronomer Certified 2.1.0-1, 2021-05-21
User-facing CHANGELOG for AC 2.1.0+astro.1 from Airflow 2.1.0:
- [astro] Continually check if we should shut down istio contaner when running K8sPodOperator ([commit](https://github.com/astronomer/airflow/commit/40a852bda))
- [astro] [AIRFLOW-5448] Handle istio-proxy for Kubernetes Pods (#62) ([commit](https://github.com/astronomer/airflow/commit/47528ff07))
- [astro-new]Override UI with Astro theme, add AC version in footer ([commit](https://github.com/astronomer/airflow/commit/3d3e35e7d))
=> Release AC 2.1.0

.circleci/generate_circleci_config.py, README.md
This commit adds the automation (included in pre-commit) for the followings:
- Updates the constraints URL when releasing a version. E.g when releasing a version we should use a pinned constraint URL (https://github.com/apache/airflow/blob/constraints-2.1.0/constraints-3.6.txt instead of Moving which is https://github.com/apache/airflow/blob/constraints-2-0/constraints-3.6.txt).
- Verifies that a CHANGELOG.md file is created within each Airflow version folder and contains entry for each AC Version
- Adds CHANGELOG.md link for each Airflow version in README.md
=> Adds automation around Changelog & Constraints

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.15/CHANGELOG.md, 1.10.15/buster/Dockerfile, 2.0.0/CHANGELOG.md, 2.0.2/CHANGELOG.md, 2.1.0/CHANGELOG.md
Astronomer Certified 1.10.15-2.dev, TBC
------------------------------------------
- KubernetesPodOperator should retry log tailing in case of interruption (#11325) ([commit](https://github.com/astronomer/airflow/commit/8848651ba))
- Correctly parse (and copy) extras with python version to metadist ([commit](https://github.com/astronomer/airflow/commit/176a2a3ec))
- Respect LogFormat when using ES logging with Json Format (#13310) ([commit](https://github.com/astronomer/airflow/commit/0dbd0f3a3))
=> Add 1.10.15-2.dev

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.1.0/CHANGELOG.md, 2.1.0/buster/Dockerfile
Astronomer Certified 2.1.0-2, 2021-06-03
- Update Kubernetes Provider to `1!1.2.1` to fix Pod hanging due to Istio container
- Don't die when masking `log.exception` when there is no exception (#16047) ([commit](https://github.com/astronomer/airflow/commit/e24040de6))
- Ensure that we don't try to mask empty string in logs (#16057) ([commit](https://github.com/astronomer/airflow/commit/d20eaa86c))
- Fill the "job_id" field for `airflow task run` without `--local`/`--raw` for KubeExecutor (#16108) ([commit](https://github.com/astronomer/airflow/commit/55fc6f6d8))
- Fix auto-refresh in tree view When webserver ui is not in ``/`` (#16018) ([commit](https://github.com/astronomer/airflow/commit/0c1d91917))
=> Release AC 2.1.0-2

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.0.2/CHANGELOG.md, 2.0.2/buster/Dockerfile
Tag: https://github.com/astronomer/airflow/releases/tag/v2.0.2%2Bastro.3
- Update Kubernetes Provider to `1!1.2.1` to fix Pod hanging due to Istio container
- Fill the "job_id" field for `airflow task run` without `--local`/`--raw` for KubeExecutor (#16108) ([commit](https://github.com/astronomer/airflow/commit/7a6492e70))
- Ensure that we don't try to mask empty string in logs (#16057) ([commit](https://github.com/astronomer/airflow/commit/215758c0a))
- Don't die when masking `log.exception` when there is no exception (#16047) ([commit](https://github.com/astronomer/airflow/commit/c4c2ab288))
- Ensure that secrets are masked no matter what logging config is in use (#15899) ([commit](https://github.com/astronomer/airflow/commit/3e61ccddd))
=> Release AC 2.0.2-3

.circleci/config.yml, .circleci/generate_circleci_config.py, 1.10.15/CHANGELOG.md, 1.10.15/buster/Dockerfile, 2.0.0/CHANGELOG.md, 2.0.0/buster/Dockerfile
Tag: https://github.com/astronomer/airflow/releases/tag/v2.0.0%2Bastro.7
Astronomer Certified 2.0.0-7, 2021-06-04
- Update Kubernetes Provider to `1!1.2.1` to fix Pod hanging due to Istio container
- Fill the "job_id" field for `airflow task run` without `--local`/`--raw` for KubeExecutor (#16108) ([commit](https://github.com/astronomer/airflow/commit/b84ded19b))
- Ensure that we don't try to mask empty string in logs (#16057) ([commit](https://github.com/astronomer/airflow/commit/a3e624ccf))
- Don't die when masking `log.exception` when there is no exception (#16047) ([commit](https://github.com/astronomer/airflow/commit/ae8613d2e))
- Ensure that secrets are masked no matter what logging config is in use (#15899) …
=> Release AC 1.10.15-2 and 2.0.0-7

1.10.10/alpine3.10/build-time-pip-constraints.txt, 1.10.10/buster/build-time-pip-constraints.txt, 1.10.7/alpine3.10/build-time-pip-constraints.txt, 1.10.7/buster/build-time-pip-constraints.txt, 2.0.0/buster/Dockerfile, 2.0.0/buster/build-time-pip-constraints.txt, 2.0.2/buster/Dockerfile, 2.0.2/buster/build-time-pip-constraints.txt, 2.1.0/buster/Dockerfile, 2.1.0/buster/build-time-pip-constraints.txt, 2.1.1/buster/Dockerfile
This PR pulls in the latest fab security manager version. The latest update resolves a security concern outlined in this issue https://app.zenhub.com/workspaces/astro-platform-board-602c68a458670000110dd641/issues/astronomer/issues/3053
=> upgrade fab sec manager to 1.6.0

2.1.1/buster/build-time-pip-constraints.txt
This should fix following issue:
```
/usr/local/lib/python3.7/site-packages/airflow/configuration.py:346 DeprecationWarning: The default_queue option in [celery] has been moved to the default_queue option in [operators] - the old setting has been used, but please update your config.
Unable to load the config, contains a configuration error.
Traceback (most recent call last):
File "/usr/local/lib/python3.7/logging/config.py", line 563, in configure
handler = self.configure_handler(handlers[name])
File "/usr/local/lib/python3.7/logging/config.py", line 736, in configure_handler
result = factory(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'host_field'
```
=> Use `1!2.0.1rc1` version of ES Provider for AC 2.1.1 dev image

.circleci/bin/test-airflow-image.py, .circleci/test-requirements.txt, 1.10.10/alpine3.10/Dockerfile, 1.10.10/buster/Dockerfile, 1.10.12/alpine3.10/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.14/buster/Dockerfile, 1.10.15/buster/Dockerfile, 1.10.7/alpine3.10/Dockerfile, 1.10.7/buster/Dockerfile, 2.0.0/buster/Dockerfile, 2.0.2/buster/Dockerfile, 2.1.0/buster/Dockerfile, 2.1.1/buster/Dockerfile
To avoid accidental Airflow upgrades, this commit/PR adds "apache-airflow==INSTALLED_VERSION" to the constraints file that is baked in the docker image.
=> Add constraint for installed Airflow version

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.1.0/CHANGELOG.md, 2.1.0/buster/Dockerfile
This commit/PR adds a nightly build for AC 2.1.0-3
https://github.com/astronomer/airflow/commits/v2-1-0/
Astronomer Certified 2.1.0-3.dev, TBC
- Avoid recursing too deep when redacting logs (#16491) ([commit](https://github.com/astronomer/airflow/commit/5398eb5ab))
- Switch to built-in data structures in SecretsMasker (#16424) ([commit](https://github.com/astronomer/airflow/commit/7e5968aaa))
- Don't fail to log if we can't redact something (#16118) ([commit](https://github.com/astronomer/airflow/commit/41ae7090d))
- Don't show stale Serialized DAGs if they are deleted in DB (#16368) ([commit](https://github.com/astronomer/airflow/commit/9d14b1d6d))
- fix: change graph focus to top of view instead of center (#16484) …
=> Add Dev image for AC 2.1.0-3

2.0.0/buster/Dockerfile, 2.0.2/buster/Dockerfile, 2.1.0/buster/Dockerfile, 2.1.1/buster/Dockerfile
Support was added in Snowflake provider: https://github.com/apache/airflow/pull/16420 to attribute usage to Partners.
This PR/commit will adds this Env var for Astronomer <-> Snowflake partnership
=> Add Env Var for Snowflake Partner Program

.circleci/bin/test-airflow, .circleci/config.yml, .circleci/generate_circleci_config.py, 2.1.1/CHANGELOG.md, 2.1.1/buster/Dockerfile
Tag: https://github.com/astronomer/airflow/releases/tag/v2.1.1%2Bastro.1
Astronomer Certified 2.1.1-1, 2021-07-02
User-facing CHANGELOG for AC 2.1.1+astro.1 from Airflow 2.1.1:
- Fix TI success/failure links ([commit](https://github.com/astronomer/airflow/commit/8f598f6fa))
- Fix TI success confirm page (#16650) ([commit](https://github.com/astronomer/airflow/commit/b0aaf266f))
- Fail tasks in scheduler when executor reports they failed (#15929) ([commit](https://github.com/astronomer/airflow/commit/fa7a14daa))
- Fix bug in mark TI success api (#16524) ([commit](https://github.com/astronomer/airflow/commit/ebae41f0e))
- Fix TI success/failure links (#16233) ([commit](https://github.com/astronomer/airflow/commit/1fb970f90))
- [astro] Continually …
=> Release AC 2.1.1-1

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.1.1/CHANGELOG.md, 2.1.1/buster/Dockerfile
Astronomer Certified 2.1.1-2, TBC
- Fix: Marking Task as success/failed ([commit](https://github.com/astronomer/airflow/commit/df1ff499c))
- Fix "Invalid JSON configuration, must be a dict" (#16648) ([commit](https://github.com/astronomer/airflow/commit/2637d9a15))
=> Add AC 2.1.1-2.dev

.circleci/bin/test-airflow
Currently we are using latest development version which is failing because it is a major version (1.0.0) and looks like alpine images are not working with that chat.
This is similar to https://github.com/astronomer/issues/issues/1491
Current failure (link: https://app.circleci.com/pipelines/github/astronomer/ap-airflow/1688/workflows/65626bd6-8423-48e5-84d6-57fcd8a16ec0/jobs/40780)
```
+ set +x
=======================
=======================
+ kubectl logs --all-containers -n airflow-14273 airflow-14273-webserver-cb86585f8-h9nst
+ tail -n 30
Error from server (BadRequest): container "webserver" in pod "airflow-14273-webserver-cb86585f8-h9nst" is waiting to start: PodInitializing
Waiting for host: airflow-14273-postgresql.airflow-14273.svc.cluster.local. 5432
Traceback (most recent call …
```
=> Use latest stable version of the Helm Chart

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.1.3/buster/Dockerfile, 2.1.3/buster/build-time-pip-constraints.txt
There were some minor issues with `2.1.3-1.dev`
- Version should be `2.1.3-1.dev` instead of `2.1.3-1-dev`
- Updates latest constraints from https://github.com/apache/airflow/blob/constraints-2-1/constraints-3.6.txt
=> Fix issues with 2.1.3-1.dev

1.10.10/buster/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.14/buster/Dockerfile, 1.10.15/buster/Dockerfile, 1.10.7/buster/Dockerfile, 2.0.0/buster/Dockerfile, 2.0.2/buster/Dockerfile, 2.1.0/buster/Dockerfile, 2.1.1/buster/Dockerfile, 2.1.3/buster/Dockerfile
Debian released Bullseye - https://www.zdnet.com/article/linux-stable-debian-11-bullseye-arrives-with-five-years-of-support/ yday and the default python images now use bullseye instead of buster:
```
root@d5c073a24b9a:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@d5c073a24b9a:/#airflow
```
This PR for now makes the default as buster explicitly:
```
❯ docker run -it python:3.7-slim-buster bash
root@cd0c5a29b1b5:/# cat etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)" …
```
=> Use Debian Buster Explicitly

.circleci/bin/test-airflow-image.py, 1.10.10/alpine3.10/include/pip-constraints.txt, 1.10.10/buster/include/pip-constraints.txt, 1.10.12/alpine3.10/include/pip-constraints.txt, 1.10.12/buster/include/pip-constraints.txt, 1.10.14/buster/include/pip-constraints.txt, 1.10.15/buster/include/pip-constraints.txt, 1.10.7/alpine3.10/include/pip-constraints.txt, 1.10.7/buster/include/pip-constraints.txt, 2.0.0/buster/include/pip-constraints.txt, 2.0.2/buster/include/pip-constraints.txt, 2.1.0/buster/include/pip-constraints.txt, 2.1.1/buster/include/pip-constraints.txt, 2.1.3/buster/build-time-pip-constraints.txt, 2.1.3/buster/include/pip-constraints.txt
related to astronomer/issues#3347
Our images currently don't work with elasticsearch>=7.14 due to https://elasticsearch-py.readthedocs.io/en/v7.14.0/transports.html#product-check-on-first-request check.
The symptoms of the error are you won't see logs in the Webserver and if you inspect (in Dev mode) in your browser, it should show you this stacktrace: https://github.com/astronomer/issues/issues/3347#issuecomment-901370036
Remediation for now, use `elasticsearch<=7.13.4`
=> Pin `elasticsearch` python client version to `7.13.4`

.circleci/bin/test-airflow-image.py, 1.10.10/buster/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.14/buster/Dockerfile, 1.10.15/buster/Dockerfile, 1.10.7/buster/Dockerfile, 2.0.0/buster/Dockerfile, 2.0.2/buster/Dockerfile, 2.1.0/buster/Dockerfile, 2.1.1/buster/Dockerfile, 2.1.3/buster/Dockerfile
fixes `CVE-2021-3711`. This does not affect 2.2.0
=> Bump epoch for buster images to fix CVEs

2.2.0/buster/Dockerfile, 2.2.0/buster/build-time-pip-constraints.txt
2.2.0 core needs celery 5, but the newest release of the celery provider wants 4 (but it should run with 5). Update constraints and avoid installing the celery provider so we have celery 5 in the image.
This is only needed until we have a version of the provider that supports celery 5.
=> 2.2.0: Keep Celery 5

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.0.0/CHANGELOG.md, 2.0.2/CHANGELOG.md, 2.0.2/buster/Dockerfile, 2.1.0/CHANGELOG.md, 2.1.0/buster/Dockerfile, 2.1.1/CHANGELOG.md, 2.1.1/buster/Dockerfile
- Releases 2.0.2-5, 2.1.0-4 and 2.1.1-3
https://github.com/astronomer/airflow/releases/tag/v2.1.1%2Bastro.3
https://github.com/astronomer/airflow/releases/tag/v2.1.0%2Bastro.4
https://github.com/astronomer/airflow/releases/tag/v2.0.2%2Bastro.5
=> Release 2.0.2-5, 2.1.0-4 and 2.1.1-3

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.2.0/buster, 2.2.1/buster
This will create images with buster tag which is needed for now as platform has "buster" hardcoded in it.
=> Re-add symlinks to produce buster images for 2.2.0 and 2.2.1

2.2.1/CHANGELOG.md
These 2 commits are in OSS 2.2.1, so we don't need to list them here as well.
=> Remove commits already in OSS 2.2.1 from 2.2.1-1

.circleci/config.yml, .circleci/generate_circleci_config.py, 2.2.0/CHANGELOG.md, 2.2.0/bullseye/Dockerfile
https://github.com/astronomer/airflow/releases/tag/v2.2.0%2Bastro.3
Astronomer Certified 2.2.0-3, 2021-11-02
- Bugfix: Check next run exists before reading data interval (apache#19307) ([commit](https://github.com/astronomer/airflow/commit/c6dea7c7bb911c6863fee1a3a6fe21c9f5106eb2))
- [astro] Reconcile orphan holding table handling ([commit](https://github.com/astronomer/airflow/commit/3b6b0da59983bbdd68686f7dd172ee951b0d66e5))
- Try to move "dangling" rows in upgradedb (apache#18953) ([commit](https://github.com/astronomer/airflow/commit/e0584063d2cd4a8a93e7d83df620f4c6b6dc1adc))
- Revert "Handle DagRuns with no execution_date or dag_id." ([commit](https://github.com/astronomer/airflow/commit/2b0bc063f03b2378d7db52aa8717ab0bbe06e89c))
- Revert "Try …
=> Release AC 2.2.0-3

.pre-commit-config.yaml
We had a race condition where the pre-commit hooks were accessing the files parallel-ly mainly for `verify-changelog-entries` and `update-dockerfiles` which caused empty files as `.read()` would entry file if the file is not closed.
This PR fixes it.
Example failure: https://app.circleci.com/pipelines/github/astronomer/ap-airflow/1969/workflows/7d9e8477-6a1c-4960-bf01-c03cf9394af5/jobs/47416
=> Run pre-commit hooks accessing file serially

.circleci/common.py, 2.1.1/buster/Dockerfile, 2.1.1/buster/build-time-pip-constraints.txt
Fix `CVE-2021-33503` in AC 2.1.1
=> Fix `CVE-2021-33503` in AC 2.1.1

.circleci/common.py, 2.1.0/buster/Dockerfile, 2.1.0/buster/build-time-pip-constraints.txt
Fixes `CVE-2021-21240` and `CVE-2021-33503`
=> Fix `CVE-2021-21240` and `CVE-2021-33503` in 2.1.0

.circleci/common.py, 2.1.4/CHANGELOG.md, 2.1.4/buster/Dockerfile, 2.2.0/CHANGELOG.md, 2.2.0/bullseye/Dockerfile, 2.2.1/CHANGELOG.md, 2.2.1/bullseye/Dockerfile
- https://github.com/astronomer/airflow/releases/tag/v2.2.1%2Bastro.2
- https://github.com/astronomer/airflow/releases/tag/v2.2.0%2Bastro.4
- https://github.com/astronomer/airflow/releases/tag/v2.1.4%2Bastro.3
Astronomer Certified 2.2.0-4, 2021-11-04
- Only mark SchedulerJobs as failed, not any jobs (#19375) ([commit](https://github.com/astronomer/airflow/commit/39ef7280940a39aa9a98ecf48422d0f876f12747))
Astronomer Certified 2.2.1-2, 2021-11-04
- Only mark SchedulerJobs as failed, not any jobs (#19375) ([commit](https://github.com/astronomer/airflow/commit/fa0b99891f56b71466299aa4729c7193e609b263))
Astronomer Certified 2.1.4-3, 2021-11-05
- Only mark SchedulerJobs as …
=> Release AC `2.2.1-2`, `2.2.0-4` and `2.1.4-3`

.circleci/config.yml
The Nightly builds were broken when we refactored CircleCi configs: https://github.com/astronomer/ap-airflow/pull/326
=> Fix the nightly Job

.circleci/config.yml
Reverts last change to fix "Max number of workflows exceeded." error described in https://support.circleci.com/hc/en-us/articles/360060934851--Max-number-of-workflows-exceeded-error
So if we want to get it working we need to use Scheduled Pipelines — https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/scheduled-pipelines.md
@blag has already created those via API
=> Revert "Fix the nightly Job"

.circleci/config.yml.j2
Based on [Scheduled Pipelines Preview Docs](https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/scheduled-pipelines.md#migrating-from-scheduled-workflows-to-scheduled-pipelines) we need to update our current workflow so selected workflows run when they are triggered via scheduled jobs vs not.
We have 2 schedules:
```
[ {
"description" : "Every morning at midnight UTC",
"name" : "every-midnight-utc",
"id" : "f9f52f7a-2fe0-478a-a633-47f7baf55cb8",
"project-slug" : "gh/astronomer/ap-airflow",
"created-at" : "2021-11-10T18:01:25.697Z",
"parameters" : {
"branch" : "master"
},
"actor" : {
"login" : "system-actor",
"name" : "Scheduled",
"id" : "d9b3fcaa-6032-405a-8c75-40079ce33c3e"
},
"timetable" : {
"per-hour" : 1,
"hours-of-day" : [ 0 ],
"days-of-week" : [ "SUN", "MON", "TUE", …
```
=> Fix Nightly jobs with CircleCI preview feature

.circleci/common.py, 2.2.2/CHANGELOG.md, 2.2.2/bullseye/Dockerfile
Astronomer Certified 2.2.2-1, 2021-11-15
User-facing CHANGELOG for AC 2.2.2+astro.1 from Airflow 2.2.2:
- [astro] Reconcile orphan holding table handling ([commit](https://github.com/astronomer/airflow/commit/c065531014fc596a251d915bfa228cfb113a51a8))
- [astro] [AIRFLOW-5448] Handle istio-proxy for Kubernetes Pods ([commit](https://github.com/astronomer/airflow/commit/11a80aede0d1b51e6c424e45805ef3b36d1debaf))
- [astro] Override UI with Astro theme, add AC version in footer ([commit](https://github.com/astronomer/airflow/commit/6a477103a4ed7358e82a1560c1c64477f85949d3))
=> Release AC 2.2.2-1

.circleci/bin/test-airflow, .circleci/bin/test-airflow-image.py, .circleci/common.py, .circleci/config.yml, .circleci/config.yml.j2, .circleci/update_dockerfiles.py, .circleci/verify_changelog_entries.py, main/bullseye/Dockerfile, main/bullseye/include/clean-airflow-logs, main/bullseye/include/entrypoint, main/bullseye/include/pip-constraints.txt, main/bullseye/include/pip.conf, main/bullseye/trivyignore
Three things need to happen:
1. The `astronomer/airflow:astro-main` branch needs to be rebased against `astronomer/airflow:main` daily/nightly.
2. New Airflow and Astronomer Certified Python artifacts (wheels) need to be built and uploaded somewhere.
3. New Docker images need to be built using those packages, tagged and labeled for QA, and uploaded to our dev image repository.
* Step 1 is implemented within a dynamically generated, scheduled pipeline here with CircleCI using an SSH deploy key due to limitations on GitHub Actions (re: scheduled workflows).
* Step 2 is implemented within the `astro-main` branch in GHA on every push event.
* Step 3 is implemented here again, to make it easy to keep the QA images built as close to production images as possible.
There will be an upcoming …
=> Add nightly builds for QA Docker images

.circleci/common.py, 2.2.2/buster
Parts of our stack still expect a tag with `buster` in it, unfortunately.
=> Add buster tag for 2.2.2

.circleci/config.yml.j2
The nightly rebase [failed](https://app.circleci.com/pipelines/github/astronomer/ap-airflow/2117/workflows/55dbab3a-9ada-49ae-9b88-c105e4048e9d/jobs/50869) because `user.name` and `user.email` were not set. This PR simply sets them.
=> Configure user.name and user.email for git rebase/commit

.circleci/bin/test-airflow-image.py, .circleci/config.yml.j2, .circleci/generate_circleci_config.py, README.md
This PR:
* Limits building "edge" images (from `astronomer/airflow:astro-main`) to only nightly builds
* Adds a YYYYMMDD image tag to the built Docker image
* Reformats the Jinja file that generates the CircleCI YAML configuration to make it easier to view both the Jinja and the generated YAML file
TODO:
It might be easier to review the commits individually (they're all small).
=> Better edge builds

.circleci/config.yml.j2
Current error (https://app.circleci.com/pipelines/github/astronomer/ap-airflow/2130/workflows/665b29ef-1ae1-4ae4-8e8d-39a9a12951a7/jobs/51312/steps):
```
#!/bin/sh -eo pipefail
#
false
```
=> Fixes nightly builds

.circleci/config.yml.j2
Emits additional information that will be useful when debugging nightly builds. Nightly workflows are somewhat difficult to test since they aren't run on PRs and aren't run super frequently, so having good/useful debug info should help surface issues when troubleshooting failed builds.
=> Emit additional info for debugging nightlies

.circleci/config.yml.j2
Judging from [this line](https://app.circleci.com/pipelines/github/astronomer/ap-airflow/2155/workflows/b6afb3d8-dae7-4e06-9d24-8ada996478fd/jobs/51585?invite=true#step-106-70) of the build output, the `extra-tags-main.txt` file didn't exist when the "Push Docker image(s)" job step ran. My best guess is that, while the build file was [persisted to the workspace](https://github.com/astronomer/ap-airflow/pull/361/files#diff-dc966af4263c0633167a31cdea357f336b51ee74e7d62d341f251d1db94a21edR545) (hat tip to @kaxil), the workspace was not loaded for the `push` step.
This PR fixes that by putting the workspace path into a Jinja variable for better reuse and attaching the workspace for the `push` job.
Additionally, this PR fixes an instance where `jq` …
=> Fix nightly build tagging

.circleci/config.yml.j2
The nightly builds are failing with the following parsing error. Example: https://app.circleci.com/pipelines/github/astronomer/ap-airflow/2171/workflows/46fce502-62ca-4975-a580-9b9c9498869a/jobs/51888
```
#!/bin/sh -eo pipefail
false
```
=> Fix nightly non-main dev builds

.circleci/config.yml.j2
For Dev but non-edge builds we still use `latest-***.build` file instead of the `*.json` file for main builds.
This PR fixes the error in https://app.circleci.com/pipelines/github/astronomer/ap-airflow/2178/workflows/b71ba65c-be64-492d-af77-40c230e6214c/jobs/51974
=> Fix dev builds

.circleci/config.yml.j2
Fixes #370.
This PR consolidates all of the Slack notifications into one message.
Previously each version emitted a separate notification, even though they all linked to the same CircleCI workflow page/ID, and from that page required an approver to approve individual jobs.
Instead of enumerating all of the possible versions in the new Slack notification, which would be pointless since they would all link to the same page, this PR only emits a single Slack notification for all versions _combined_ and includes only a single link to the overall workflow. So approvers will still be brought to the exact same page where they need to approve individual version builds.
A few notes about the screenshots below:
* the …
=> Consolidate Slack notifications into one message

.circleci/config.yml.j2
This PR linkifies the CircleCI project and branch fields, and changes the pull request field to a direct link to the Git SHA on GitHub.
We don't make releases from pull requests, so the pull request environment variables weren't set it CircleCI anyway.
I also expect us to separate out some of the older releases into separate branch(es) at some point, so while the branch field isn't currently really useful at the moment, I expect it to be in the future.
Partial screenshots:
=> Linkify things and swap out pull request for Git SHA info

.circleci/config.yml.j2
Fixes the build by pulling the version info from the `latest-main.build.json` file instead of the (out of date) `latest-main.build` file.
We should probably remove the `latest-main.build` file from the server so it causes louder errors in the future.
=> Pull the VERSION build arg from the correct build info file

.circleci/config.yml.j2
Resolves #334, resolves #354.
This PR does three things:
The UPSERT attempts to INSERT data into the table, and when the unique constraint on the `version_1` column is violated, it then attempts to UPDATE the same row using the latest tag from the rejected ("excluded") data and moving the previous latest tag to the previous tag:
```sql
INSERT INTO tag_version (version_1,    latest_tag, previous_tag, is_latest)
VALUES             ('${release}', '${tag}',   NULL,         << parameters.edge_build >>)
ON CONFLICT (version_1)
DO UPDATE SET   latest_tag = EXCLUDED.latest_tag,
previous_tag = tag_version.latest_tag;
```
The `is_latest` column is used to identify versions built from edge builds. It is always `true` for edge builds and `false` for versioned …
=> Send Slack notifications and update QA database on new releases

.circleci/config.yml.j2
One character fix for the Slack notification for release approval.
Currently blocking the AC 2.2.3-1 release.
=> Fix JSON syntax in Slack notification

.circleci/config.yml.j2
We should only push to QA Cluster if it is a dev build
=> Fix failing master

.circleci/config.yml.j2
Fixes release builds by include the `qa` context to the `push` jobs in the non-nightly workflow.
=> Fix release builds

2.2.3/CHANGELOG.md
The release date was missing in https://github.com/astronomer/ap-airflow/pull/381
(depends on #389)
Only review last commit - https://github.com/astronomer/ap-airflow/pull/389/commits/4428ac5df70460687240d649904822fbadbc3242
=> Update release date for `2.2.3-1`

repackage-providers.py
This PR allows us to just a provider a url, and it will find whether a provider with a given version needs to be repackaged or not (by checking for the provider with that version on astronomer's PyPI).
Code change is just in a single commit: https://github.com/astronomer/ap-airflow/pull/391/commits/96d3045835bcdd132419b81b949f3c47ef10e1b3
The other commits are formatting related (Black + Import reordering)
=> Improve provider repackage script

.circleci/config.yml.j2, 2.1.0/buster/build-time-pip-constraints.txt, 2.1.0/buster/trivyignore, 2.1.1/buster/build-time-pip-constraints.txt, 2.1.1/buster/trivyignore, 2.1.3/buster/build-time-pip-constraints.txt, 2.1.3/buster/trivyignore, 2.1.4/buster/build-time-pip-constraints.txt, 2.1.4/buster/trivyignore, 2.2.0/bullseye/build-time-pip-constraints.txt, 2.2.1/bullseye/build-time-pip-constraints.txt, 2.2.2/bullseye/build-time-pip-constraints.txt, 2.2.3/bullseye/build-time-pip-constraints.txt
This fixes, or ignores, all the CVE issues in `2.1.0` through `2.2.3`.
Note, this changes the behavior of snyk to only exit non-zero if there are _fixable_ issues. As of now, none of the issues found in debian 10/11 have fixes upstream, so there is no easy resolution to them.
=> Move CVE fixes for `2.1.0-2.2.3`

1.10.15/buster/Dockerfile, 2.1.0/buster/Dockerfile, 2.1.1/buster/Dockerfile, 2.1.3/buster/Dockerfile, 2.1.4/buster/Dockerfile, 2.2.0/bullseye/Dockerfile, 2.2.1/bullseye/Dockerfile, 2.2.2/bullseye/Dockerfile, 2.2.3/bullseye/Dockerfile
Add a `io.astronomer.docker.fab_security_manager.version` label so it is easier to identify the version of the FAB SM in an image.
This also updates the images to the latest version of the FAB SM.
=> Add `io.astronomer.docker.fab_security_manager.version` label

.circleci/config.yml.j2
Fixes builds by adding an explicit `image` subcommand to the `trivy` command.
=> Fix trivy invocation by adding 'image' subcommand

1.10.12/alpine3.10/Dockerfile, 1.10.12/buster/Dockerfile, 1.10.14/buster/Dockerfile, 1.10.15/buster/Dockerfile, 2.1.0/buster/Dockerfile, 2.1.1/buster/Dockerfile, 2.1.3/buster/Dockerfile, 2.1.4/buster/Dockerfile, 2.2.0/bullseye/Dockerfile, 2.2.1/bullseye/Dockerfile, 2.2.2/bullseye/Dockerfile, 2.2.3/bullseye/Dockerfile, 2.2.4/bullseye/Dockerfile
This is to support implicit namespace change in https://github.com/astronomer/astronomer-fab-securitymanager/releases/tag/v1.8.3
=> Bump Fab Security Manager to 1.8.3

README.md
Since rebranding and doc reorg, this link got broken.
=> Fix broken link for AC Lifecycle

.circleci/config.yml.j2
QA needs to identify the exact commit that the Airflow packages and Docker images are built from.
Previously we included Git information from the GitHub Actions workflow that identified the `astro-main` branch and its HEAD commit SHA. Not only was this slightly misleading because the corresponding label name, `org.apache.airflow.git.commit_sha`, indicated that the commit was from the `apache/airflow:main` branch, it was also incorrect because it didn't identify the exact commit from `astronomer/airflow:main` or even `astronomer/airflow:astro-main` that the Python package and Docker images were built from.
The branch and commit SHA from `astro-main` identified the information for what the package and images were built _by_, but not what they were …
=> Split out built_from and built_by Docker image labels

.circleci/common.py, README.md
closes https://github.com/astronomer/issues-airflow/issues/169
Based on our [new versioning policy](https://docs.astronomer.io/software/ac-support-policy/#end-of-maintenance-date), there is no point in building older images.
I have kept the docker image and changelogs for now but we should remove them after 28 Feb, probably just keep changelogs (🤷 ).
=> Only build LTS and last two versions

1.10.15/buster/build-time-pip-constraints.txt, 1.10.15/buster/trivyignore
Fixes:
- CVE-2021-22570
Ignores:
- CVE-2021-23727
- CVE-2021-33503
- CVE-2021-41265
=> Fix or ignore CVEs for 1.10.15

1.10.15/buster/Dockerfile, 2.1.4/buster/Dockerfile
=> Update dependecies to get latest expat

2.2.4/bullseye/Dockerfile
=> Update 2.2.4 dependencies to get latest expat

.circleci/common.py, 1.10.15/buster/Dockerfile, 2.1.4/buster/Dockerfile, 2.2.4/bullseye/Dockerfile
=> Bump FAB Security Manager to 1.8.4

main/bullseye/Dockerfile
This bumps Fab Security Manager for main and also adds constraints for main build
=> Fix constraints & bump Fab Security Manager for `main` build

.circleci/bin/test-airflow-image.py, .circleci/config.yml.j2
closes https://github.com/astronomer/issues-airflow/issues/167
Alternative to #415.
This PR refactors the generated CircleCI config to always build, scan, and test images before pausing for approval to push images. For steps that build a versioned release of AC it preserves the CircleCI approvals and corresponding Slack approval notifications for pushing new images and the new build Slack notification to the QA channel. For dev and edge/`main` builds it skips the CircleCI/Slack approval process, but also keeps the new build Slack notifications to the QA channel.
The new build notifications to the QA channel may be too noisy. I'm happy to change this if necessary.
=> Always build, test, and scan, and only require approval to push for version releases

.circleci/config.yml.j2, .circleci/new_dev_build_slack_notification.json.j2, .circleci/push.bash.j2, README.md
* Fixes instructions for adding a new distro
* Documents all of the different types of builds and how they are triggered
* Always tags `main.dev` images
* Adds labels to images containing the CircleCI workflow ID that build the image and a link to the workflow
* Adjusts the suffix of the nightly build tags to `-nightly+YYYYMMDD`
* Uses the list of approvers that's already defined
* Removes (incorrect) tag from the Slack notification
=> Tweaks, fixups, and general cleanup

.circleci/config.yml.j2
Whiteline was being chopped of:
Before:
```
--label com.circleci.workflow.id="${CIRCLE_WORKFLOW_ID}"--label com.circleci.workflow.url="https://app.circleci.com/pipelines/workflows/${CIRCLE_WORKFLOW_ID}"
```
After:
```
--label com.circleci.workflow.id="${CIRCLE_WORKFLOW_ID}"
--label com.circleci.workflow.url="https://app.circleci.com/pipelines/workflows/${CIRCLE_WORKFLOW_ID}"
```
=> Fix failing nightly

.circleci/push.bash.j2
Docker image tags cannot contain `+` characters and have to match this regex: `[\w][\w.-]{0,127}`. This PR tweaks the logic a bit, but it also swaps out the `+` for a `-`.
Unfortunately this means that the `-YYYYMMDD` suffix is now considered part of the "prerelease" section of the version string instead of the "build [identifier]" section of the version string, but until Docker relaxes their tag format a bit, we're stuck with this.
This should also fix the nightly build failures ([1](https://app.circleci.com/pipelines/github/astronomer/ap-airflow/2687/workflows/edde0849-a201-478f-8a7b-da623a44b3c7/jobs/63426) and [2](https://app.circleci.com/pipelines/github/astronomer/ap-airflow/2687/workflows/edde0849-a201-478f-8a7b-da623a44b3c7/jobs/63427)).
The …
=> Fix build string in Docker image tag

.circleci/config.yml.j2, README.md
=> Always build version nightlies

.circleci/bin/test-airflow, .circleci/bin/test-airflow-image.py, .circleci/common.py, .circleci/config.yml.j2, .circleci/update_dockerfiles.py, README.md
This PR switches the `.dev` version string suffix to `-dev` so that dev version strings are valid SemVer.
=> Ensure that numbered dev version strings are SemVer

.circleci/bin/test-airflow
Follow up on #443, this fixes the way the `dev` identifier in version strings is stripped off.
=> Fix chopping the dev suffix from version strings

.circleci/bin/test-airflow-image.py
In #442 I [changed the nightly builds to always build, tag, and push nightly images for versioned releases](https://github.com/astronomer/ap-airflow/pull/442/files#diff-dc966af4263c0633167a31cdea357f336b51ee74e7d62d341f251d1db94a21edR229).
However, I didn't update the tests.
Since that change creates additional nightly builds, we need to expand the way that we extract the AC version from the full AC version string.
There's a tiny bit of repetition between lines 84 and 87, but I couldn't figure out a cleaner way to get the logic to work for all cases, and I included an example case.
This should fix the [nightly build test failures](https://app.circleci.com/pipelines/github/astronomer/ap-airflow/2727/workflows/60cf49b2-20f8-408a-b28a-1431ba3c6019).
=> Fix tests now that we build release version nightlies

.circleci/bin/test-airflow-image.py
This PR fixes the tests for the nightly builds by ensuring backwards compatibility with `.dev` in version strings.
=> Split on both -dev and .dev

.circleci/bin/test-airflow-image.py, .circleci/common.py, 1.10.15/buster/Dockerfile, 2.1.4/buster/Dockerfile, 2.2.4/bullseye/Dockerfile
This fixes CVEs for the following:
2.2.4: glibc, mariadb and locales
2.1.4 & 1.10.15: mariadb and gmp
=> Update dependencies to fix CVEs

main/bullseye/Dockerfile
Bump FAB security manager to 1.9.0 for main build
=> Bump FAB security manager to 1.9.0 for main build

main/bullseye/Dockerfile
This PR is a fixup for #458, it bumps astronomer-fab-securitymanager to 1.9.0 for the `devel` build stage as well as the `main` build stage bumped by #458.
=> Also update the astronomer-fab-securitymanager to 1.9.0 in devel build stage

.circleci/bin/check-different-arg-values.sh, .pre-commit-config.yaml
This PR adds a pre-commit check for differing values in version ARGs in Dockerfiles.
This would catch issues like #458, corrected in #459, where we only updated one of the two `ASTRONOMER_FAB_SECURITY_MANAGER_VERSION` ARGs.
It's dirty messy Bash, but it works.
Example output:
```
Checking that all ARG variable values agree with each other in Dockerfiles.......................Failed
- hook id: check-different-arg-values
- exit code: 1
Found multiple ARG ASTRONOMER_FAB_SECURITY_MANAGER_VERSION in main/bullseye/Dockerfile with different values:
117:ARG ASTRONOMER_FAB_SECURITY_MANAGER_VERSION="1.9.1"
146:ARG ASTRONOMER_FAB_SECURITY_MANAGER_VERSION="1.9.2"
Please update both/all ARG ASTRONOMER_FAB_SECURITY_MANAGER_VERSION directives to the same value in …
```
=> Check for different Dockerfile version ARG values

1.10.15/buster/Dockerfile, 2.1.4/buster/Dockerfile, 2.2.5/bullseye/Dockerfile, main/bullseye/Dockerfile
Docker was emitting a warning about blank continuation lines:
```
Removing intermediate container 23828e259861
[WARNING]: Empty continuation line found in:
RUN sed -i     -e 's/^run_as_user =.*/run_as_user = 50000/g'     -e 's/^lazy_load_plugins =.*/lazy_load_plugins = False/g'     -e 's/^update_fab_perms =.*/update_fab_perms = False/g'     -e 's/^auth_backend =.*/auth_backend = astronomer.flask_appbuilder.current_user_backend/g'     -e 's/^operation_timeout =.*/operation_timeout = 10.0/g'     /usr/local/lib/python${PYTHON_MAJOR_MINOR_VERSION}/site-packages/airflow/config_templates/default_airflow.cfg
[WARNING]: Empty continuation lines will become errors in a future release.
[Warning] One or more build-args [BUILD_NUMBER REPO_BRANCH] were not …
```
=> Silence a Docker warning (soon to be an error)

.circleci/build_approval_slack_notification.json.j2, .circleci/config.yml.j2, .circleci/new_dev_build_slack_notification.json.j2
This PR has a few fixups for our Slack notifications.
1. Fixes the hotlink for the embedded Astronomer logo. We now use the same image, but [hosted from an Imgur album](https://imgur.com/a/CYRKjQ3), which supports hotlinking:
2. Fixed (I think) the at-mentions for new dev build Slack notifications.
3. Adds a much better descriptions in image alt texts (helpful for any blind or vision handicapped Astronomers).
=> Fixup slack notifications

1.10.15/buster/Dockerfile, 2.1.4/buster/Dockerfile, 2.2.5/bullseye/Dockerfile, 2.3.0/bullseye/Dockerfile, main/bullseye/Dockerfile
Fix Trivy scans for all released versions.
The `main` build is still failing due to a bad constraints file, not due to any of these changes.
=> Update deps to fix gzip/liblzma5 CVE-2022-1271

2.3.0/bullseye/Dockerfile, main/bullseye/Dockerfile
Bumps astronomer-fab-securitymanager to 1.9.1 so we have [this fix](https://github.com/astronomer/astronomer-fab-securitymanager/pull/39) for both 2.3.0 and main images.
=> Update astronomer-fab-securitymanager to 1.9.1 for 2.3.0 and main images

2.3.0/bullseye/include/entrypoint, main/bullseye/include/entrypoint
In 2.3.0, there are some configuration changes that lead to deprecation
warnings. Instead of having tons of these in platform, let's move/update
the config in the entrypoint to avoid extra noise. These can be removed
once platform is setting the new config properly.
=> Silence 2.3.0 deprecation warnings

common/Dockerfile.onbuild-buster
Reported on a call by a customer
=> Fix bug where packages.txt in Windows line-endings didn't work

.circleci/push.bash.j2
If you don't, you could try fetching packages that are no longer on the
mirror.
=> Update before install with apt-get

.circleci/bin/test-airflow
Expands the lines logged to stdout to 100, up from 30. It's 3x more verbose, but it really helps include information that would otherwise be trampled by tracebacks, like the [recent build failures](https://app.circleci.com/pipelines/github/astronomer/ap-airflow/3215/workflows/df3b3077-666a-4181-a18a-c5c5be28304a/jobs/72413).
30 lines:
```
=======================
+ kubectl logs --all-containers -n airflow-31526 airflow-31526-run-airflow-migrations-lb785
+ tail -n 30
File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 569, in run_env
util.load_python_file(self.dir, "env.py")
File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
module = load_module_py(module_id, path)
File …
```
=> Expand saved logs for easier debugging

.circleci/config.yml.j2, .circleci/kickoff_qa_tests.sh
* Kick off QA smoke tests from the `test` branch (so I don't have to commit and push to `master` to test fixes)
* Fix logic that gates kicking off tests for dev builds
* Explicitly check out the code before using it
* Fix the order of arguments to `kickoff_qa_tests.sh`
* Fix checking arguments in `kickoff_qa_tests.sh`
* Improve the logic to update the code from `origin` - fast forward rebases/merges are now supported
* Update the correct file
* Install and use `yq` to update the YAML config files instead of blindly using `sed` - this should be much more robust!
* Configure a git user and email address
* Allow empty QA repo commits - this allows us to force test runs by adding and pushing empty commits
* Add a `DRY_RUN` variable to prevent pushing …
=> Fix and improve triggering QA tests

.circleci/config.yml.j2
This PR makes the generated Bash a bit easier to read when it's finally rendered before running in CircleCI.
Before:
```
#!/bin/bash -eo pipefail
set -xe
mkdir -p saved-images/"$(dirname 'ap-airflow:main')"
docker build $([[ "true" == "true" ]] && printf -- "--no-cache") \
--tag 'ap-airflow:main' \
--label io.astronomer.docker.build_time="$(date +%s)" \
--label io.astronomer.repo.commit_sha="${CIRCLE_SHA1}" \
--label io.astronomer.repo.url="${CIRCLE_REPOSITORY_URL}" \
--label io.astronomer.ci.build_url="${CIRCLE_BUILD_URL}" \
--file 'main/bullseye/Dockerfile' \
--build-arg VERSION=$(jq -r '.output.astronomer_certified.package.version' </tmp/workspace/latest-main.build.json) --label org.apache.airflow.ci.build.date=$(jq -r '.date' …
```
=> Experiment better bash formatting

2.3.3/bullseye/Dockerfile
Fixes Trivy complaints.
The CI failure is due to an unrelated constraints issue in `main`.
=> Bump 2.3.3 dependency numbers to fix trivy issues

.circleci/config.yml.j2, .circleci/kickoff_qa_tests.sh
This PR sets the `image_tag` key when kicking off smoke and regression tests.
=> Also configure image_tag in QA tests

.circleci/config.yml.j2, .circleci/new_build_slack_approval.json.j2, .circleci/new_dev_build_slack_notification.json.j2, .circleci/regression_test_slack_approval.json.j2, .circleci/regression_test_slack_notification.json.j2, .circleci/smoke_test_slack_notification.json.j2
This PR adds better links to QA test workflows, and also improves (IMO) all of our Slack messages a bit.
I removed some section dividers, and added some at the end of the messages - this should hopefully help visually separate notifications about different versions, since we one message for each AC version in a run. I also utilized the (new?) `header` block that renders text larger than the rest of the message, which should further help out.
=> Better links and Slack messages

.circleci/common.py
We can stop building from `main` now. 🎉
In an attempt to minimize churn, I didn't change any of the template branching logic, since I don't know that that buys us a whole lot anymore.
=> Stop building from main

2.3.3/bullseye/build-time-pip-constraints.txt
This fixes a critical bug with AWS secret manager.
cc @collinmcnulty 
=> Bump amazon provider to 4.1.0

common/Dockerfile.onbuild-bullseye
This was fixed a while back for our buster images (#482), but was missed for bullseye.
=> Fix bug where packages.txt in Windows line-endings didn't work on bullseye

.circleci/config.yml.j2
We can simplify the dependecy chain by properly setting the required jobs based on whether we are a dev build or not. Dev builds don't need approval (thus push depends on the tests/scans), while releases do (approval depends on tests/scans, push on approval).
=> Simplify CI dependencies

.circleci/bin/test-airflow, .circleci/bin/test-airflow-image.py, .circleci/common.py, .circleci/config.yml.j2, .circleci/generate_circleci_config.py, .circleci/update_dockerfiles.py
This PR adds scans for released builds to the nightly "builds"/pipelines.
I think that Trivy and Snyk will automatically pull images that are not in the local cache, but I'm not 100% sure about this, so I'll monitor the nightly jobs and fix things as needed.
=> Scan released versions nightly

.circleci/config.yml.j2
Fix the nightlies. If we can't load images before scans, pull them from the registry. This allows us to scan images that we haven't just built, which is what happens for builds we've already released.
=> Fix nightly scans

.circleci/config.yml.j2
Update the nightly scans for released builds to scan images from the quay.io remote registry.
I duplicated the `scan-snyk-docker-image` command as a job, since DRY isn't as important for this repo as it's approaching EOL. Otherwise I would try to ensure that the different snyk scans only use a single job.
=> Fix nightly scans again

2.3.4/bullseye/include/entrypoint, 2.4.3/bullseye/include/entrypoint
We intended to support puckel style config via `EXECUTOR`, but there was a ` ` vs `=` typo meaning it never actually functioned. Let's just remove it as no one is relying on it.
=> Remove broken `EXECUTOR` support

.circleci/common.py, 2.3.4/CHANGELOG.md, 2.3.4/bullseye/Dockerfile, 2.4.3/CHANGELOG.md, 2.4.3/bullseye/Dockerfile
I just want to call out explicitly that these images have major version bumps in the amazon and google providers to fix CVEs.
=> Release 2.4.3-6 and 2.3.4-11
