astronomer/ap-airflow

- 1.10.5/alpine3.10/Dockerfile
- 1.10.5/alpine3.10/include/entrypoint
- 1.10.5/buster/Dockerfile
- 1.10.5/buster/include/entrypoint
fix astronomer/issues#507
related PR astronomer/helm.astronomer.io#238
> Add tighten control of airflow migrations

- 1.10.5/rhel/Dockerfile
- 1.10.5/rhel/include/clean-airflow-logs
- 1.10.5/rhel/include/entrypoint
- 1.10.5/rhel/include/pip-constraints.txt
- 1.10.5/rhel/python3.6.sh
Adding airflow docker for rhel
> Adding airflow docker for rhel

- .circleci/config.yml
- 1.10.5/buster/Dockerfile
- README.md
- cve-whitelist.yaml
fix https://github.com/astronomer/issues/issues/615
by creating whitelist and waiting for patch in buster image;
> Fix buster image

- 1.10.5/alpine3.10/Dockerfile
- 1.10.5/buster/Dockerfile
- 1.10.5/rhel7/Dockerfile
> Bump astronomer-airflow-scripts to v0.0.4

- 1.10.5/alpine3.10/include/entrypoint
- 1.10.5/buster/include/entrypoint
- 1.10.5/rhel7/include/entrypoint
fix https://github.com/astronomer/issues/issues/652#issuecomment-564823312
> only check if AIRFLOW__CORE__SQL_ALCHEMY_CONN is set than loop and wait

- .circleci/config.yml
- .circleci/config.yml.j2
- .circleci/generate_circleci_config.py
- 1.10.5/rhel7/onbuild/Dockerfile
> RHEL7 for Airflow 1.10.5

- cve-whitelist.yaml
Docker images don't run their own kernel, so these aren't an issue for
us
> Accept/Ignore Kernel vulnerabilities in RHEL image

- .circleci/generate_circleci_config.py
- 1.10.6/alpine3.10/Dockerfile
- 1.10.6/buster/Dockerfile
> Release 1.10.6-2

- .circleci/test-airflow-image.py
- .gitignore
- 1.10.5/alpine3.10/include/pip-constraints.txt
- 1.10.5/buster/include/pip-constraints.txt
- 1.10.5/rhel7/include/pip-constraints.txt
- 1.10.6/alpine3.10/include/pip-constraints.txt
- 1.10.6/buster/include/pip-constraints.txt
- 1.10.7/alpine3.10/include/pip-constraints.txt
- 1.10.7/buster/include/pip-constraints.txt
@ashb for this comment: https://astronomerteam.slack.com/archives/CLRKTKHGU/p1580586195005300
n/a
> Add test to confirm Redis image version

- README.md
> It's "CEA", not "Certified Airflow"

- 1.10.7/CHANGELOG.md
Adds Changelog for AC 1.10.7-7
> Add Changelog for 1.10.7-7

- 1.10.5/CHANGELOG.md
- 1.10.5/alpine3.10/Dockerfile
- 1.10.5/buster/Dockerfile
- 1.10.5/rhel7/Dockerfile
https://github.com/astronomer/airflow/releases/tag/1.10.5-6
Since this is not a part of AC, I haven't released a dev image, we should test it manually.
> Release Astro Airflow 1.10.5-6

- .circleci/config.yml
- .circleci/config.yml.j2
- 1.10.10.dev/alpine3.10/Dockerfile
- 1.10.10.dev/buster/Dockerfile
Because CircleCI was using cache it was using the same whl package to build the dev docker images
> Dont use cache when building docker images

- 1.10.10.dev/alpine3.10/include/pip-constraints.txt
- 1.10.5/alpine3.10/include/pip-constraints.txt
- 1.10.6/alpine3.10/include/pip-constraints.txt
- 1.10.7/alpine3.10/include/pip-constraints.txt
> Pin dep of papermill to ensure we don't get pyarrow pulled in on Alpine

- 1.10.10.dev/alpine3.10/include/pip-constraints.txt
- 1.10.10.dev/buster/include/pip-constraints.txt
- 1.10.5/alpine3.10/include/pip-constraints.txt
- 1.10.5/buster/include/pip-constraints.txt
- 1.10.5/rhel7/include/pip-constraints.txt
- 1.10.6/alpine3.10/include/pip-constraints.txt
- 1.10.6/buster/include/pip-constraints.txt
- 1.10.7/alpine3.10/include/pip-constraints.txt
- 1.10.7/buster/include/pip-constraints.txt
> Constraint version of WTForms to non-broken version

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.7/CHANGELOG.md
- 1.10.7/alpine3.10/Dockerfile
- 1.10.7/buster/Dockerfile
1.10.7-9 tag: https://github.com/astronomer/airflow/releases/tag/v1.10.7%2Bastro.9
> Release Astro Certified 1.10.7-9

- .circleci/config.yml
- .circleci/config.yml.j2
- .circleci/generate_circleci_config.py
- .circleci/test-requirements.txt
- .pre-commit-config.yaml
- 1.10.7/CHANGELOG.md
Add [PreCommit](https://pre-commit.com/) Hooks to test (& fix) the following:
- Checks for consistency between config.yml and config.yml.j2
- Correct YAML syntax
- Missing End of file line
- Trailing Whitespaces
> Add Precommit Hooks & test them in CI

- .circleci/config.yml
- .circleci/config.yml.j2
Nightly build was failing, this PR fixes it
> Fix nightly build for 1.10.7 DEV Image

- 1.10.5/rhel7/Dockerfile
Fixing this image till we decide to remove it (@schnie Happy for us to remove the image ? )
> Fix RHEL Image

- .circleci/config.yml
- .circleci/config.yml.j2
- .circleci/generate_circleci_config.py
- 1.10.10/alpine3.10/trivyignore
- 1.10.10/buster/trivyignore
- 1.10.5/alpine3.10/trivyignore
- 1.10.5/buster/trivyignore
- 1.10.5/rhel7/trivyignore
- 1.10.6/alpine3.10/trivyignore
- 1.10.6/buster/trivyignore
- 1.10.7/CHANGELOG.md
- 1.10.7/alpine3.10/Dockerfile
- 1.10.7/alpine3.10/trivyignore
- 1.10.7/buster/Dockerfile
- 1.10.7/buster/trivyignore
- cve-whitelist.yaml
Tag: https://github.com/astronomer/airflow/releases/tag/v1.10.7%2Bastro.12
> Update 1.10.7 Alpine image to install Python 3.7.7

- 1.10.7/CHANGELOG.md
Commit: https://github.com/astronomer/ap-airflow/commit/33da5f5e3dab63bc875c2552909c67356c328bcb was added to 1.10.7-9
> Update Changelog for 1.10.7-9

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.7/CHANGELOG.md
- 1.10.7/alpine3.10/Dockerfile
- 1.10.7/buster/Dockerfile
Tag: https://github.com/astronomer/airflow/releases/tag/v1.10.7+astro.12
> Release Astro Certified 1.10.7-12

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.5/CHANGELOG.md
- 1.10.5/alpine3.10/Dockerfile
- 1.10.5/buster/Dockerfile
- 1.10.5/rhel7/Dockerfile
- 1.10.7/CHANGELOG.md
Tag: https://github.com/astronomer/airflow/releases/tag/1.10.5-8
> Release Astro Certified 1.10.5-8

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.10/alpine3.10/Dockerfile
- 1.10.10/buster/Dockerfile
Only change:
- [[AIRFLOW-6959] Use NULL as dag.description default value (apache#7593)](https://github.com/astronomer/airflow/commit/548f4be32dbd4d222eb5666e83a9629ef360610e)
> Add 1.10.10-3.dev

- .circleci/bin/test-airflow-image.py
- common/Dockerfile.onbuild-alpine3.10
- common/Dockerfile.onbuild-buster
- common/Dockerfile.onbuild-rhel7
If they do this it will break various things, so we don't want to let
them do this
> Block people from upgrading Airflow in the image

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.5/alpine3.10/Dockerfile
- 1.10.5/buster/Dockerfile
- 1.10.5/rhel7/Dockerfile
https://github.com/astronomer/airflow/releases/tag/1.10.5-9.dev
> Add 1.10.5-9.dev

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.5/CHANGELOG.md
- 1.10.5/alpine3.10/Dockerfile
- 1.10.5/buster/Dockerfile
- 1.10.5/rhel7/Dockerfile
https://github.com/astronomer/airflow/releases/tag/1.10.5-9
> Release AC 1.10.5-9

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.7/CHANGELOG.md
- 1.10.7/alpine3.10/Dockerfile
- 1.10.7/buster/Dockerfile
https://github.com/astronomer/airflow/releases/tag/v1.10.7%2Bastro.13
> Release AC 1.10.7+astro.13

- 1.10.10/CHANGELOG.md
- 1.10.5/CHANGELOG.md
astronomer/airflow -> astronomer/ap-airflow
> Fix broken links in Changelog

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.10/CHANGELOG.md
- 1.10.10/alpine3.10/Dockerfile
- 1.10.10/buster/Dockerfile
Changelog:
- Enable Dag Serialization by default ([commit](https://github.com/astronomer/airflow/commit/d587b6f))
> Add AC 1.10.10-4.dev

- .circleci/bin/test-airflow-image.py
- .circleci/generate_circleci_config.py
- 1.10.10/alpine3.10/Dockerfile
- 1.10.10/buster/Dockerfile
- 1.10.5/alpine3.10/Dockerfile
- 1.10.5/buster/Dockerfile
- 1.10.5/rhel7/Dockerfile
- 1.10.7/alpine3.10/Dockerfile
- 1.10.7/buster/Dockerfile
fixes https://github.com/astronomer/issues/issues/1572
> Run Kubernetes Worker Pods as astro user

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.10/alpine3.10/Dockerfile
- 1.10.10/buster/Dockerfile
- 1.10.7/alpine3.10/Dockerfile
- 1.10.7/buster/Dockerfile
https://github.com/astronomer/airflow/commits/v1-10-10
https://github.com/astronomer/airflow/commits/v1-10-7
> Add AC 1.10.7-15.dev and 1.10.10-5.dev

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.7/CHANGELOG.md
- 1.10.7/alpine3.10/Dockerfile
- 1.10.7/buster/Dockerfile
https://github.com/astronomer/airflow/releases/tag/v1.10.7%2Bastro.15
> Release AC 1.10.7-15

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.10/alpine3.10/include/pip-constraints.txt
- 1.10.12/alpine3.10/include/pip-constraints.txt
- 1.10.5/CHANGELOG.md
- 1.10.5/alpine3.10/Dockerfile
- 1.10.5/alpine3.10/include/pip-constraints.txt
- 1.10.5/buster/Dockerfile
- 1.10.5/rhel7/Dockerfile
- 1.10.7/alpine3.10/include/pip-constraints.txt
https://github.com/astronomer/airflow/releases/tag/1.10.5-11
> Release AC 1.10.5-11

- .circleci/bin/install-ci-tools
- .circleci/bin/test-airflow
- .circleci/bin/test-airflow-image.py
- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.10/alpine3.10/trivyignore
- 1.10.10/buster/trivyignore
- 1.10.12/alpine3.10/trivyignore
- 1.10.12/buster/trivyignore
- 1.10.5/alpine3.10/trivyignore
- 1.10.5/buster/trivyignore
- 1.10.5/rhel7/trivyignore
- 1.10.7/alpine3.10/trivyignore
- 1.10.7/buster/trivyignore
- 2.0.0/CHANGELOG.md
- 2.0.0/buster/Dockerfile
- 2.0.0/buster/include/clean-airflow-logs
- 2.0.0/buster/include/entrypoint
- 2.0.0/buster/include/pip-constraints.txt
- 2.0.0/buster/include/pip.conf
- 2.0.0/buster/trivyignore
- common/Dockerfile.onbuild-buster
https://github.com/astronomer/airflow/tree/v2-0-0
> Add 2.0.0-1.dev image

- .circleci/config.yml
- .circleci/config.yml.j2
closes https://github.com/astronomer/issues/issues/2135
> Push non-dev images to Dev Docker repo

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.13/CHANGELOG.md
- 1.10.13/buster/Dockerfile
- 1.10.13/buster/include/clean-airflow-logs
- 1.10.13/buster/include/entrypoint
- 1.10.13/buster/include/pip-constraints.txt
- 1.10.13/buster/include/pip.conf
- 1.10.13/buster/trivyignore
Add dev image for AC 1.10.13-1
https://github.com/astronomer/airflow/commits/v1-10-13
> Add 1.10.13-1.dev

- 1.10.10/alpine3.10/Dockerfile
- 1.10.10/buster/Dockerfile
- 1.10.12/alpine3.10/Dockerfile
- 1.10.12/buster/Dockerfile
- 1.10.13/buster/Dockerfile
- 1.10.5/alpine3.10/Dockerfile
- 1.10.5/buster/Dockerfile
- 1.10.5/rhel7/Dockerfile
- 1.10.7/alpine3.10/Dockerfile
- 1.10.7/buster/Dockerfile
- 2.0.0/buster/Dockerfile
https://github.com/astronomer/astronomer-airflow-scripts/releases/tag/v0.0.5
> Bump astronomer_airflow_scripts to 0.0.5

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.13/CHANGELOG.md
- 1.10.13/buster/Dockerfile
Astronomer Certified 1.10.13-2.dev
-----------------------------------------------
- BugFix: Tasks with depends_on_past or task_concurrency are stuck ([commit](https://github.com/astronomer/airflow/commit/56e446811))
- Fix issue with empty Resources in executor_config ([commit](https://github.com/astronomer/airflow/commit/7ef6354da))
> Add AC 1.10.13-2

- README.md
Move from "Astronomer Certified" to "Astronomer Core"
> Revise nomenclature

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.10/CHANGELOG.md
- 1.10.10/alpine3.10/Dockerfile
- 1.10.10/buster/Dockerfile
- 1.10.7/CHANGELOG.md
- 1.10.7/alpine3.10/Dockerfile
- 1.10.7/buster/Dockerfile
https://github.com/astronomer/airflow/releases/tag/v1.10.7%2Bastro.16
https://github.com/astronomer/airflow/releases/tag/v1.10.10%2Bastro.6
> Release AC 1.10.7-16 & 1.10.10-6

- 2.0.0/buster/Dockerfile
We already install elasticsearch deps via extras so need to separately install it
> Remove redundant provider: elasticsearch

- .circleci/config.yml
- .circleci/config.yml.j2
Part of https://github.com/astronomer/issues/issues/2324
This commit will push the images to https://quay.io/repository/astronomer/core?tab=tags
> Publish Releases to astronomer/core repo too

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.10/alpine3.10/Dockerfile
- 1.10.10/buster/Dockerfile
- 1.10.14/buster/Dockerfile
- 1.10.7/alpine3.10/Dockerfile
- 1.10.7/buster/Dockerfile
This patch contains fixes for Istio and 1.10.14-2 contains some additional fixes  (https://github.com/astronomer/airflow/commits/v1-10-14)
> Add Dev versions for 1.10.7-17, 1.10.10-7 and 1.10.14-2

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.12/alpine3.10/Dockerfile
- 1.10.12/buster/Dockerfile
https://github.com/astronomer/airflow/commits/v1-10-12
> Add 1.10.12-3.dev

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 2.0.0/CHANGELOG.md
- 2.0.0/buster/Dockerfile
- README.md
The Image have already been released and published y'day.
> Release 2.0.0-1 AC Images

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 2.0.0/buster/Dockerfile
https://github.com/astronomer/airflow/commits/v2-0-0
```
b20b5bc70 (HEAD -> v2-0-0, origin/v2-0-0) Stop sending Callback Requests if no callbacks are defined on DAG (#13163)
060fe16bd Filter DagRuns with Task Instances in removed State while Scheduling (#13165)
4c80a59cd Bump datatables.net from 1.10.21 to 1.10.22 in /airflow/www (#13143)
ce7d8b6a0 Update to AC v2.0.0.dev1+astro.2
```
> Add 2.0.0-2.dev

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.10/CHANGELOG.md
- 1.10.10/alpine3.10/Dockerfile
- 1.10.10/buster/Dockerfile
- 1.10.12/CHANGELOG.md
- 1.10.12/alpine3.10/Dockerfile
- 1.10.12/buster/Dockerfile
- 1.10.14/CHANGELOG.md
- 1.10.14/buster/Dockerfile
- 1.10.7/CHANGELOG.md
- 1.10.7/alpine3.10/Dockerfile
- 1.10.7/buster/Dockerfile
https://github.com/astronomer/airflow/releases/tag/v1.10.7%2Bastro.17
https://github.com/astronomer/airflow/releases/tag/v1.10.10%2Bastro.7
https://github.com/astronomer/airflow/releases/tag/v1.10.12%2Bastro.3
https://github.com/astronomer/airflow/releases/tag/v1.10.14%2Bastro.2
> Release AC 1.10.7-17, 1.10.10-7, 1.10.12-3 & 1.10.14-2

- 2.0.1/CHANGELOG.md
2.0.1 1.dev - Fix End of Lines in ChangeLog
> AC 2.0.1-1.dev - Fix End of Lines Static Check failure

- 2.0.1/buster/Dockerfile
Use 2.0.1 constraints file for AC 2.0.1
> Use 2.0.1 constraints file for AC 2.0.1

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 2.0.0/CHANGELOG.md
- 2.0.0/buster/Dockerfile
Tag: https://github.com/astronomer/airflow/releases/tag/v2.0.0%2Bastro.3
Astronomer Certified 2.0.0-3, 2021-02-16
-----------------------------------------
- Bugfix: Return XCom Value in the XCom Endpoint API ([commit](https://github.com/astronomer/airflow/commit/c2c9c06b3))
- BugFix: Dag-level Callback Requests were not run ([commit](https://github.com/astronomer/airflow/commit/4412aba55))
- Increase the default ``min_file_process_interval`` to decrease CPU Usage ([commit](https://github.com/astronomer/airflow/commit/6de02157f))
- Stop creating duplicate Dag File Processors ([commit](https://github.com/astronomer/airflow/commit/4ced807ab))
- Fix drop_user_and_chart migration rule for MySQL ([commit](https://github.com/astronomer/airflow/commit/ebbbc62b542c32b791dd265338d253ed1c1c19f9))
- …
> Release AC 2.0.0-3

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.15/CHANGELOG.md
- 1.10.15/buster/Dockerfile
- 1.10.15/buster/include/clean-airflow-logs
- 1.10.15/buster/include/entrypoint
- 1.10.15/buster/include/pip-constraints.txt
- 1.10.15/buster/include/pip.conf
- 1.10.15/buster/trivyignore
Releasing 1.10.15-1.dev
Tag: https://github.com/astronomer/airflow/releases/tag/v1.10.15%2Bastro.1
> Release 1.10.15-1.dev

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.15/buster/Dockerfile
- 1.10.15-1 is not released yet and is only a dev version
- nightly build should be created for this version
> Fix 1.10.15-1.dev

- 1.10.15/buster/Dockerfile
Looks like some of the changes were missed in 1.10.15 that Constance introduced in (#217).
This PR adds those changes
> Add missing changes for 1.10.15

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 2.0.0/buster/Dockerfile
This commit adds 2.0.0-4.dev image from
https://github.com/astronomer/airflow/commits/v2-0-0
> Add 2.0.0-4.dev

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 2.0.0/buster/Dockerfile
This commit adds 2.0.0-5.dev image from
https://github.com/astronomer/airflow/commits/v2-0-0
> Add 2.0.0-5.dev

- .circleci/config.yml
- .circleci/config.yml.j2
Currently the scanner is failing to run because of the issue 
https://github.com/arminc/clair-local-scan/issues/57
We will plan to replace it later with SnykPro
> Disable Clair Scans

- .circleci/config.yml
This was introduced in https://github.com/astronomer/ap-airflow/pull/246
> Fix static check

- .circleci/config.yml
- .circleci/config.yml.j2
Add the docker.io context after deleting the variables from the project local vars.
Related to https://github.com/astronomer/issues/issues/2841
> added docker.io and new codecov context

- .circleci/config.yml
- .circleci/config.yml.j2
> Fix buster docker context2

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 2.1.0/CHANGELOG.md
- 2.1.0/buster/Dockerfile
- 2.1.0/buster/include/clean-airflow-logs
- 2.1.0/buster/include/entrypoint
- 2.1.0/buster/include/pip-constraints.txt
- 2.1.0/buster/include/pip.conf
- 2.1.0/buster/trivyignore
> Push 2.1.0.Dev Docker Image

- repackage-providers.py
- Make `version` optional
- Allow repackaging wheels from local directory
- Don't repackage Kubernetes provider from a URL as it won't have Istio patch.
> Improvements in Providers Repackage Script

- 2.1.1/CHANGELOG.md
https://github.com/astronomer/airflow/releases/tag/v2.1.1%2Bastro.2
> Update Changelog for 2.1.1-2

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.10/CHANGELOG.md
- 1.10.10/alpine3.10/Dockerfile
- 1.10.10/alpine3.10/build-time-pip-constraints.txt
- 1.10.10/buster/Dockerfile
- 1.10.10/buster/build-time-pip-constraints.txt
- 1.10.12/CHANGELOG.md
- 1.10.12/alpine3.10/Dockerfile
- 1.10.12/buster/Dockerfile
- 1.10.14/CHANGELOG.md
- 1.10.14/buster/Dockerfile
- 1.10.15/buster/Dockerfile
- 1.10.7/CHANGELOG.md
- 1.10.7/alpine3.10/Dockerfile
- 1.10.7/alpine3.10/build-time-pip-constraints.txt
- 1.10.7/buster/Dockerfile
- 1.10.7/buster/build-time-pip-constraints.txt
- 2.0.0/buster/Dockerfile
- 2.0.2/buster/Dockerfile
- 2.1.0/buster/Dockerfile
- 2.1.1/buster/Dockerfile
- Releases 1.10.7-19, 1.10.10-9, 1.10.12-5 and 1.10.14-4
- Fixes PyJWT conflicts
> Release 1.10.7-19, 1.10.10-9, 1.10.12-5 and 1.10.14-4

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 2.1.3/CHANGELOG.md
- 2.1.3/buster/Dockerfile
- 2.1.3/buster/build-time-pip-constraints.txt
Depends on https://github.com/astronomer/ap-airflow/pull/295
https://github.com/astronomer/airflow/releases/tag/v2.1.3%2Bastro.1
> Release AC 2.1.3-1

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 2.0.0/CHANGELOG.md
- 2.0.0/buster/Dockerfile
> Release 2.0.0-9

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 2.1.4/CHANGELOG.md
- 2.1.4/buster/Dockerfile
- 2.1.4/buster/build-time-pip-constraints.txt
Tag: https://github.com/astronomer/airflow/releases/tag/v2.1.4%2Bastro.1
> Release 2.1.4-1

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.10/CHANGELOG.md
- 1.10.10/alpine3.10/Dockerfile
- 1.10.10/buster/Dockerfile
- 1.10.12/CHANGELOG.md
- 1.10.12/alpine3.10/Dockerfile
- 1.10.12/buster/Dockerfile
- 1.10.14/CHANGELOG.md
- 1.10.14/buster/Dockerfile
- 1.10.15/CHANGELOG.md
- 1.10.15/buster/Dockerfile
- 2.0.0/CHANGELOG.md
- 2.0.0/buster/Dockerfile
- 2.0.2/CHANGELOG.md
- 2.0.2/buster/Dockerfile
- 2.1.0/CHANGELOG.md
- 2.1.0/buster/Dockerfile
- 2.1.1/CHANGELOG.md
- 2.1.1/buster/Dockerfile
- 2.1.3/CHANGELOG.md
- 2.1.3/buster/Dockerfile
- 2.1.4/CHANGELOG.md
- 2.1.4/buster/Dockerfile
- 2.2.0/CHANGELOG.md
Publishes Istio patches with the same changes in - https://github.com/astronomer/airflow/commit/ad5a98ff8 for following AC Versions:
- 1.10.10-10
- 1.10.12-6
- 1.10.14-5
- 1.10.15-4
- 2.0.0-10
- 2.0.2-6
- 2.1.0-5
- 2.1.1-4
- 2.1.3-2
- 2.1.4-2
> Publish patches for Istio bug

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- 1.10.10/CHANGELOG.md
- 1.10.10/alpine3.10/Dockerfile
- 1.10.10/buster/Dockerfile
- 1.10.12/CHANGELOG.md
- 1.10.12/alpine3.10/Dockerfile
- 1.10.12/buster/Dockerfile
- 1.10.14/CHANGELOG.md
- 1.10.14/buster/Dockerfile
- 1.10.15/CHANGELOG.md
- 1.10.15/buster/Dockerfile
- 2.0.0/CHANGELOG.md
- 2.0.0/buster/Dockerfile
- 2.0.2/CHANGELOG.md
- 2.0.2/buster/Dockerfile
- 2.1.0/CHANGELOG.md
- 2.1.0/buster/Dockerfile
- 2.1.1/CHANGELOG.md
- 2.1.1/buster/Dockerfile
- 2.1.3/CHANGELOG.md
- 2.1.3/buster/Dockerfile
- 2.1.4/CHANGELOG.md
- 2.1.4/buster/Dockerfile
- 2.2.0/CHANGELOG.md
Releases Istio patches with the same changes in - https://github.com/astronomer/airflow/commit/ad5a98ff8 for following AC Versions:
- 1.10.10-10
- 1.10.12-6
- 1.10.14-5
- 1.10.15-4
- 2.0.0-10
- 2.0.2-6
- 2.1.0-5
- 2.1.1-4
- 2.1.3-2
- 2.1.4-2
> Release Patch Versions for Istio fix

- 2.2.0/CHANGELOG.md
- 2.2.1/CHANGELOG.md
> Update 2.2.1-1 and 2.2.0-3 changelogs

- .circleci/common.py
- 2.2.0/CHANGELOG.md
- 2.2.0/bullseye/Dockerfile
- 2.2.1/CHANGELOG.md
- 2.2.1/bullseye/Dockerfile
Time to cut `2.2.1-2.dev` and `2.2.0-4.dev`.
> Add 2.2.1-2.dev and 2.2.0-4.dev

- .circleci/common.py
- 2.1.0/CHANGELOG.md
- 2.1.1/CHANGELOG.md
- 2.1.3/CHANGELOG.md
- 2.1.3/buster/Dockerfile
Add Changelogs for `2.1.0-6.dev`, `2.1.1-5.dev` and `2.1.3-3.dev`
> Add Changelogs for `2.1.0-6.dev`, `2.1.1-5.dev` and `2.1.3-3.dev`

- 2.2.0/bullseye/Dockerfile
- 2.2.1/bullseye/Dockerfile
Fix ``CVE-2021-23214`` in 2.2.0 and 2.2.1 series
> Fix ``CVE-2021-23214`` in 2.2.0 and 2.2.1 series

- 1.10.10/alpine3.10/build-time-pip-constraints.txt
- 1.10.10/buster/build-time-pip-constraints.txt
- 1.10.12/alpine3.10/build-time-pip-constraints.txt
- 1.10.12/buster/build-time-pip-constraints.txt
- 1.10.14/buster/build-time-pip-constraints.txt
- 1.10.15/buster/Dockerfile
- 1.10.15/buster/build-time-pip-constraints.txt
- 2.0.0/buster/build-time-pip-constraints.txt
- 2.1.3/buster/build-time-pip-constraints.txt
The following CVE's were fixed:
- CVE-2021-42771
- CVE-2020-14343
- CVE-2021-20270
- CVE-2021-27291
- CVE-2020-36242
- CVE-2021-21240
> Fix a bunch of Python Package CVEs 

- .circleci/config.yml.j2
Fixes:
- The git push after rebase was missing `--force`
- The build.json step was not persisting the data for the other job to use
> Fix bugs with edge builds

- .circleci/common.py
- 2.1.4/CHANGELOG.md
- 2.1.4/buster/Dockerfile
- 2.2.0/CHANGELOG.md
- 2.2.0/bullseye/Dockerfile
- 2.2.1/CHANGELOG.md
- 2.2.1/bullseye/Dockerfile
- 2.2.2/CHANGELOG.md
- 2.2.2/bullseye/Dockerfile
New dev releases for:
* `2.2.2-2.dev`
* `2.2.1-3.dev`
* `2.2.0-5.dev`
* `2.1.4-4.dev`
> Add `2.2.2-2.dev`, `2.2.1-3.dev`, `2.2.0-5.dev`, and `2.1.4-4.dev`

- .circleci/config.yml.j2
> Fix getting version from build file

- .circleci/update_dockerfiles.py
- 1.10.10/alpine3.10/Dockerfile
- 1.10.10/buster/Dockerfile
- 1.10.12/alpine3.10/Dockerfile
- 1.10.12/buster/Dockerfile
- 1.10.14/buster/Dockerfile
- 1.10.15/buster/Dockerfile
- 2.0.0/buster/Dockerfile
- 2.0.2/buster/Dockerfile
- 2.1.0/buster/Dockerfile
- 2.1.1/buster/Dockerfile
- 2.1.3/buster/Dockerfile
- 2.1.4/buster/Dockerfile
- 2.2.0/bullseye/Dockerfile
- 2.2.1/bullseye/Dockerfile
- 2.2.2/bullseye/Dockerfile
- 2.2.3/bullseye/Dockerfile
Keep copyright year upto date with the pre-commit
> Update the copyright year to 2021

- .circleci/config.yml.j2
> Fix Git SHA link syntax

- .circleci/test-requirements.txt
> Bump test requirements

- .circleci/common.py
- 2.2.3/CHANGELOG.md
- 2.2.3/bullseye/Dockerfile
> Release AC `2.2.3-1`

- 1.10.10/buster/Dockerfile
- 1.10.12/buster/Dockerfile
- 1.10.14/buster/Dockerfile
- 1.10.15/buster/Dockerfile
- 2.0.0/buster/Dockerfile
- 2.0.2/buster/Dockerfile
- 2.1.0/buster/Dockerfile
- 2.1.1/buster/Dockerfile
- 2.1.3/buster/Dockerfile
- 2.1.4/buster/Dockerfile
- 2.2.0/bullseye/Dockerfile
- 2.2.1/bullseye/Dockerfile
- 2.2.2/bullseye/Dockerfile
- 2.2.3/bullseye/Dockerfile
- main/bullseye/Dockerfile
Should fix [`CVE-2021-43618`](https://avd.aquasec.com/nvd/cve-2021-43618/)
> Fix `CVE-2021-43618`

- .circleci/config.yml.j2
https://stackoverflow.com/a/19670094
> Fix bash to properly fix failing master

- .circleci/pre-commit-scripts/copyright.py
- .circleci/update_dockerfiles.py
- .pre-commit-config.yaml
- 1.10.10/alpine3.10/Dockerfile
- 1.10.10/buster/Dockerfile
- 1.10.12/alpine3.10/Dockerfile
- 1.10.12/buster/Dockerfile
- 1.10.14/buster/Dockerfile
- 1.10.15/buster/Dockerfile
- 2.0.0/buster/Dockerfile
- 2.0.2/buster/Dockerfile
- 2.1.0/buster/Dockerfile
- 2.1.1/buster/Dockerfile
- 2.1.3/buster/Dockerfile
- 2.1.4/buster/Dockerfile
- 2.2.0/bullseye/Dockerfile
- 2.2.1/bullseye/Dockerfile
- 2.2.2/bullseye/Dockerfile
- 2.2.3/bullseye/Dockerfile
- common/Dockerfile.onbuild-alpine3.10
- common/Dockerfile.onbuild-bullseye
- common/Dockerfile.onbuild-buster
- main/bullseye/Dockerfile
> Update Copyright Year

- .circleci/config.yml.j2
This PR adds Snyk for scanning images for known security vulnerabilities
closes https://github.com/astronomer/issues-airflow/issues/40
> Add Snyk for security scanning

- 2.1.4/buster/build-time-pip-constraints.txt
- 2.2.0/bullseye/build-time-pip-constraints.txt
- 2.2.1/bullseye/build-time-pip-constraints.txt
- 2.2.2/bullseye/build-time-pip-constraints.txt
`CVE-2021-41265` and `CVE-2021-23727`
> Fix CVEs for `2.2.2-2`, `2.2.1-3`, `2.2.0-5`, and `2.1.4-5`

- clean-artifacts.py
Add script to clean old dev artifacts from GCS storage 
This script helps to clean old dev artifacts from a bucket
> Add script to clean old dev artifacts from GCS storage

- 2.2.0/bullseye/build-time-pip-constraints.txt
- 2.2.1/bullseye/build-time-pip-constraints.txt
- 2.2.2/bullseye/build-time-pip-constraints.txt
> Bump FAB to `3.4.3`

- repackage-providers.py
> Fix an import error in repackaging provider script

- .circleci/common.py
- 2.2.3/bullseye/Dockerfile
> Add `2.2.3-2.dev`

- 1.10.12/alpine3.10/Dockerfile
- 1.10.12/buster/Dockerfile
- 1.10.14/buster/Dockerfile
- 1.10.15/buster/Dockerfile
- 2.0.0/buster/Dockerfile
- 2.0.2/buster/Dockerfile
- 2.1.0/buster/Dockerfile
- 2.1.1/buster/Dockerfile
- 2.1.3/buster/Dockerfile
- 2.1.4/buster/Dockerfile
- 2.2.0/bullseye/Dockerfile
- 2.2.1/bullseye/Dockerfile
- 2.2.2/bullseye/Dockerfile
- 2.2.3/bullseye/Dockerfile
- 2.2.4/bullseye/Dockerfile
https://github.com/astronomer/astronomer-fab-securitymanager/releases/tag/v1.18.2
> Bump Fab Security Manager

- .circleci/common.py
- 2.2.4/bullseye/Dockerfile
> Release `2.2.4-1`

- .circleci/common.py
- 1.10.15/buster/Dockerfile
- 2.1.4/buster/Dockerfile
> Release dev images for 2.1.0-5 and 1.10.15-5

- .circleci/common.py
- 1.10.15/CHANGELOG.md
- 1.10.15/buster/Dockerfile
- 2.1.4/CHANGELOG.md
- 2.1.4/buster/Dockerfile
> Release `1.10.15-5` and `2.1.4-5`

- repackage-providers.py
There was a bug which prevented the GitHub provided to be uploaded
> Fix bug in repackaging providers script

- 1.10.15/CHANGELOG.md
- 2.1.4/CHANGELOG.md
- 2.2.4/CHANGELOG.md
> Release `2.2.4-2`, `2.1.4-6`, and `1.10.15-6`

- .circleci/common.py
- 1.10.15/buster/Dockerfile
- 2.1.4/buster/Dockerfile
- 2.2.4/bullseye/Dockerfile
> Release `2.2.4-2`, `2.1.4-6`, and `1.10.15-6` (fixed)

- .circleci/config.yml.j2
closes https://github.com/astronomer/issues-airflow/issues/172
> Stop using cache for main builds

- .circleci/bin/test-airflow-image.py
- .circleci/common.py
- 2.2.4/bullseye/Dockerfile
- 2.2.4/bullseye/build-time-pip-constraints.txt
This PR adds test for Istio and fixes the missing Istio commit
> Add missed Istio patch for `2.2.4-2`

- 1.10.15/buster/Dockerfile
- 2.2.4/bullseye/Dockerfile
- 2.2.4/bullseye/build-time-pip-constraints.txt
- main/bullseye/Dockerfile
This will reinstall all the dependencies including the fixed kubernetes provider
> Burst cache for dependencies

- .circleci/common.py
- 2.2.4/CHANGELOG.md
- 2.2.4/bullseye/Dockerfile
> Release `2.2.4-3`

- 1.10.15/buster/Dockerfile
- 2.1.4/buster/Dockerfile
> Update deps to fix zlib CVE-2018-25032

- .circleci/common.py
- 1.10.15/CHANGELOG.md
- 1.10.15/buster/Dockerfile
- 2.1.4/CHANGELOG.md
- 2.1.4/buster/Dockerfile
- 2.2.4/CHANGELOG.md
- 2.2.4/bullseye/Dockerfile
Time to release `2.2.4-4`, `2.1.4-7`, and `1.10.15-7`!
> Release `2.2.4-4`, `2.1.4-7`, and `1.10.15-7`

- .circleci/common.py
- 2.2.5/CHANGELOG.md
- 2.2.5/bullseye/Dockerfile
> Release ``2.2.5-1``

- .circleci/common.py
- 2.2.5/CHANGELOG.md
- 2.2.5/bullseye/Dockerfile
Create a dev image for 2.2.5-3.
+ [x] to follow all of the directions in the `README.md`
+ [x] that there are Dockerfiles in all base image directories
+ [x] that all of the new or modified Dockerfiles build successfully
> Add 2.2.5-3-dev

- .gitignore
Things get added here when repackaging providers and should be ignored.
> Add `in` to `.gitignore`

- .circleci/common.py
- 2.3.0/CHANGELOG.md
- 2.3.0/bullseye/Dockerfile
- 2.3.0/bullseye/build-time-pip-constraints.txt
> Release AC `2.3.0-1`

- .circleci/common.py
- 2.3.0/bullseye/Dockerfile
> Bump FAB SM to 1.9.2

- .circleci/common.py
- 2.3.0/CHANGELOG.md
- 2.3.0/bullseye/Dockerfile
> Release `2.3.0-2`

- 1.10.15/buster/include/entrypoint
- 2.1.4/buster/include/entrypoint
- 2.2.5/bullseye/include/entrypoint
- 2.3.0/bullseye/include/entrypoint
- main/bullseye/include/entrypoint
This PR/commit will aid in debugging and finding the root cause faster when debugging to
finding why the migration are not running for example.
Has it connected to the DB or is it just the last log line it has printed.
> Add logs after successful connection to DB in the entrypoint

- .circleci/common.py
- 2.3.0/CHANGELOG.md
- 2.3.0/bullseye/Dockerfile
> Release 2.3.0-3

- .circleci/common.py
- 2.3.0/bullseye/Dockerfile
> Add 2.3.0-4-dev

- .circleci/common.py
- 2.3.0/CHANGELOG.md
- 2.3.0/bullseye/Dockerfile
> Release 2.3.0-4

- .circleci/common.py
- 2.3.0/CHANGELOG.md
- 2.3.0/bullseye/Dockerfile
> Release 2.3.0-5

- .circleci/common.py
- 2.3.0/bullseye/Dockerfile
> Add 2.3.0-6-dev

- .circleci/common.py
- 2.3.1/CHANGELOG.md
- 2.3.1/bullseye/Dockerfile
- 2.3.1/bullseye/trivyignore
> Release `2.3.1-1`

- .circleci/common.py
- 2.3.2/CHANGELOG.md
- 2.3.2/bullseye/Dockerfile
> Release AC 2.3.2-1

- 2.3.2/bullseye/build-time-pip-constraints.txt
We need the new ES provider to properly take advantage of the fixed log template behavior.
> Update elasticsearch provider to 4.0.0

- .circleci/common.py
- 1.10.15/buster/Dockerfile
- 2.1.4/buster/Dockerfile
- 2.2.5/bullseye/Dockerfile
- 2.3.2/bullseye/Dockerfile
- main/bullseye/Dockerfile
Also, bumped FAB security manager in some images
> Update dependencies to fix CVEs

- .circleci/common.py
- 1.10.15/CHANGELOG.md
- 1.10.15/buster/Dockerfile
- 2.1.4/CHANGELOG.md
- 2.1.4/buster/Dockerfile
- 2.2.5/CHANGELOG.md
- 2.2.5/bullseye/Dockerfile
- 2.3.2/CHANGELOG.md
- 2.3.2/bullseye/Dockerfile
> Release 1.10.15-8, 2.1.4-8,2.2.5-3,2.3.2-2

- .circleci/common.py
- 2.3.3/CHANGELOG.md
- 2.3.3/bullseye/Dockerfile
> Release AC `2.3.3-1`

- .circleci/common.py
- 2.1.4/buster/Dockerfile
> Add 2.1.4-9-dev

- .circleci/common.py
- 1.10.15/buster/Dockerfile
> Fix openssl cve in 1.10.15

- .circleci/common.py
- 1.10.15/CHANGELOG.md
- 1.10.15/buster/Dockerfile
- 2.1.4/CHANGELOG.md
- 2.1.4/buster/Dockerfile
> Release AC 2.1.4-9,1.10.15-9

- .circleci/common.py
- 2.3.3/bullseye/Dockerfile
> Add 2.3.3-2dev

- .circleci/common.py
- 2.3.3/CHANGELOG.md
- 2.3.3/bullseye/Dockerfile
> Release 2.3.3-2

- 1.10.15/buster/Dockerfile
- 2.1.4/buster/Dockerfile
Bump dependencies to fix image scans.
> Fix trivy issue

- .circleci/bin/test-airflow
> Fix tests - we now have airflow-operator on the repo

- 2.3.4/bullseye/build-time-pip-constraints.txt
> Bump Mako in 2.3.4 to fix CVE

- .circleci/config.yml.j2
Since the push is already gated by successful tests, we don't need to check for successful tests again.
> Smoke test only relies on pushes

- .circleci/common.py
- 2.3.4/CHANGELOG.md
- 2.3.4/bullseye/Dockerfile
> Release 2.3.4-2

- .circleci/config.yml.j2
> Fix nightly CI: we only scan, no building

- 2.1.4/buster/Dockerfile
- 2.3.4/bullseye/Dockerfile
Fixes some but not all scanner issues.
> Bump upgrade epoch numbers to upgrade all system packages

- .circleci/common.py
- .circleci/update_dockerfiles.py
- 2.4.1/bullseye/Dockerfile
> Release 2.4.1-1

- .circleci/common.py
- 2.3.4/bullseye/Dockerfile
> Add 2.3.4-3-dev

- .circleci/common.py
- 2.3.4/CHANGELOG.md
- 2.3.4/bullseye/Dockerfile
> Releasing 2.3.4-3

- 2.3.4/CHANGELOG.md
- 2.3.4/bullseye/trivyignore
> Add changelog for 2.3.4-4-dev

- .circleci/common.py
- 2.4.2/CHANGELOG.md
- 2.4.2/bullseye/Dockerfile
> Release AC 2.4.2+astro.1

- .circleci/common.py
- 2.1.4/CHANGELOG.md
- 2.1.4/buster/Dockerfile
- 2.1.4/buster/build-time-pip-constraints.txt
- 2.1.4/buster/trivyignore
- 2.3.4/CHANGELOG.md
- 2.3.4/bullseye/Dockerfile
- 2.3.4/bullseye/trivyignore
> Add `2.1.4-10` and `2.3.4-6` dev images

- .circleci/common.py
- 2.1.4/CHANGELOG.md
- 2.1.4/buster/Dockerfile
- 2.3.4/CHANGELOG.md
- 2.3.4/bullseye/Dockerfile
> Release 2.1.4-10 and 2.3.4-6.

- .circleci/common.py
- 2.4.3/CHANGELOG.md
- 2.4.3/bullseye/Dockerfile
> Release AC 2.4.3-1

- .circleci/common.py
- 2.4.3/bullseye/Dockerfile
> Add 2.4.3-2-dev

- .circleci/common.py
- 2.3.4/CHANGELOG.md
- 2.3.4/bullseye/Dockerfile
- 2.3.4/bullseye/build-time-pip-constraints.txt
- 2.3.4/bullseye/trivyignore
- 2.4.3/CHANGELOG.md
- 2.4.3/bullseye/Dockerfile
- 2.4.3/bullseye/build-time-pip-constraints.txt
> New 2.4.3 and 2.3.4 dev images

- .circleci/common.py
- 2.3.4/bullseye/Dockerfile
- 2.4.3/bullseye/Dockerfile
> Release 2.4.3-2 and 2.3.4-7

- .circleci/config.yml.j2
- 2.3.4/bullseye/Dockerfile
- 2.4.3/bullseye/Dockerfile
- common/Dockerfile.onbuild-bullseye
- common/Dockerfile.onbuild-buster
- main/bullseye/Dockerfile
> Rotate ssh keys, remove snyk and rebase-main

- .circleci/common.py
- 2.3.4/bullseye/Dockerfile
- 2.3.4/bullseye/build-time-pip-constraints.txt
- 2.4.3/bullseye/Dockerfile
- 2.4.3/bullseye/build-time-pip-constraints.txt
> New 2.3.4-8 and 2.4.3-3 dev images

- .circleci/common.py
- 2.3.4/CHANGELOG.md
- 2.3.4/bullseye/Dockerfile
- 2.4.3/CHANGELOG.md
- 2.4.3/bullseye/Dockerfile
> Release 2.4.3-3 and 2.3.4-8

- .circleci/common.py
- 2.3.4/bullseye/Dockerfile
- 2.4.3/bullseye/Dockerfile
> New 2.4.3-4 and 2.3.4-9 dev images

- .circleci/common.py
- 2.3.4/CHANGELOG.md
- 2.3.4/bullseye/Dockerfile
- 2.4.3/CHANGELOG.md
- 2.4.3/bullseye/Dockerfile
> Release 2.4.3-4 and 2.3.4-9

- .circleci/common.py
- 2.3.4/CHANGELOG.md
- 2.3.4/bullseye/Dockerfile
- 2.3.4/bullseye/build-time-pip-constraints.txt
- 2.3.4/bullseye/trivyignore
- 2.4.3/CHANGELOG.md
- 2.4.3/bullseye/Dockerfile
- 2.4.3/bullseye/build-time-pip-constraints.txt
- 2.4.3/bullseye/trivyignore
> Add 2.4.3-5 and 2.3.4-10 dev images

- .circleci/common.py
- 2.3.4/CHANGELOG.md
- 2.3.4/bullseye/Dockerfile
- 2.4.3/CHANGELOG.md
- 2.4.3/bullseye/Dockerfile
> Release 2.4.3-5 and 2.3.4-10

- .circleci/common.py
- 2.3.4/CHANGELOG.md
- 2.3.4/bullseye/Dockerfile
- 2.3.4/bullseye/build-time-pip-constraints.txt
- 2.3.4/bullseye/trivyignore
- 2.4.3/CHANGELOG.md
- 2.4.3/bullseye/Dockerfile
- 2.4.3/bullseye/build-time-pip-constraints.txt
- 2.4.3/bullseye/trivyignore
> Add new 2.4.3-6 and 2.3.4-11 dev images
